(()=>{'use strict';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const lang=()=>document.documentElement.lang==='en'?'en':'fa';
const tx=(fa,en)=>lang()==='en'?en:fa;
const articles=[
 {id:'plan-week',cat:'planning',min:6,fa:{title:'هفته‌ات را سبک ولی دقیق بچین',desc:'یک روش ساده برای اینکه برنامه‌ریزی به لیست آرزوها تبدیل نشود.',body:['اول سه نتیجهٔ مهم هفته را بنویس؛ نه سی کار ریز.','هر نتیجه را به یک قدم ۲۰ تا ۴۵ دقیقه‌ای تبدیل کن و فقط همان قدم بعدی را وارد تسک‌ها کن.','برای کارهای غیرضروری یک لیست «بعداً» داشته باش تا برنامهٔ امروز خفه نشود.']},en:{title:'Plan a lighter, sharper week',desc:'A simple way to stop planning from becoming a wish list.',body:['Write the three outcomes that matter most this week—not thirty tiny tasks.','Turn each outcome into one 20–45 minute next action and put only that next action in Tasks.','Keep a Later list for non-essential work so Today stays breathable.']}},
 {id:'focus-reset',cat:'focus',min:5,fa:{title:'وقتی تمرکزت پخش شده، از صفر ریست کن',desc:'ریست کوتاه پنج‌دقیقه‌ای قبل از Pomodoro بعدی.',body:['همهٔ تب‌های غیرضروری را ببند و فقط یک مقصد روی صفحه نگه دار.','یک جمله بنویس: «تا پایان این جلسه فقط …».','تایمر را کوتاه‌تر از حد معمول شروع کن؛ شروع دوباره مهم‌تر از طول جلسه است.']},en:{title:'Reset when your focus is scattered',desc:'A five-minute reset before the next Pomodoro.',body:['Close every unnecessary tab and leave one destination on screen.','Write one sentence: “Until this session ends, I only …”.','Start with a shorter timer than usual; restarting matters more than session length.']}},
 {id:'habit-small',cat:'habits',min:7,fa:{title:'عادت را آن‌قدر کوچک کن که بهانه جا نشود',desc:'چطور نسخهٔ حداقلی عادت را طراحی کنی و زنجیره را زنده نگه داری.',body:['حداقل موفقیت را تعریف کن: یک صفحه، پنج حرکت، یک لیوان آب.','بعد از انجام حداقل، ادامه دادن اختیاری است؛ این کار مقاومت شروع را کم می‌کند.','اگر سه روز پشت سر هم حداقل را انجام دادی، اندازهٔ عادت را خیلی کم بالا ببر.']},en:{title:'Make the habit too small to dodge',desc:'Design a minimum version that keeps the chain alive.',body:['Define the minimum win: one page, five reps, one glass of water.','After the minimum, continuing is optional; this lowers starting resistance.','After three consistent days, increase the habit only a little.']}},
 {id:'read-better',cat:'reading',min:8,fa:{title:'کمتر بخوان، بیشتر به خاطر بسپار',desc:'سه حرکت برای مطالعه‌ای که بعداً واقعاً یادت بماند.',body:['قبل از فصل یک سؤال مشخص بساز تا ذهنت دنبال جواب بگردد.','بعد از هر بخش، بدون نگاه‌کردن دو خط از حافظه بنویس.','یک بریده یا یادداشت را به Book Clips بفرست تا بعداً راحت‌تر برگردی.']},en:{title:'Read less, remember more',desc:'Three moves that make reading stick.',body:['Create one concrete question before the chapter so your mind looks for an answer.','After each section, write two lines from memory without looking back.','Save one quote or note to Book Clips so you can revisit it later.']}},
 {id:'energy-day',cat:'wellbeing',min:6,fa:{title:'روزت را با انرژی مدیریت کن، نه فقط با ساعت',desc:'کارهای سنگین را وقتی بگذار که مغزت واقعاً توانش را دارد.',body:['دو بازه‌ای را که معمولاً انرژی بیشتری داری پیدا کن.','کار عمیق را به یکی از همان بازه‌ها بده و کارهای سبک را به زمان افت انرژی منتقل کن.','خواب، آب و تمرین را به‌عنوان سیگنال ببین، نه عدد برای قضاوت خودت.']},en:{title:'Manage energy, not only hours',desc:'Put demanding work where your brain can actually carry it.',body:['Find the two windows when your energy is usually strongest.','Place deep work in one of those windows and move shallow work to lower-energy time.','Treat sleep, water and exercise as signals—not numbers to judge yourself with.']}}
];
const cats={all:['همه','All'],planning:['برنامه‌ریزی','Planning'],focus:['تمرکز','Focus'],habits:['عادت','Habits'],reading:['مطالعه','Reading'],wellbeing:['انرژی','Energy']};
let filter='all',query='';
function icon(cat){return ({planning:'🗓',focus:'✦',habits:'↻',reading:'◈',wellbeing:'☼'})[cat]||'✦'}
function card(a){const c=a[lang()];return '<article class="blog-card" data-blog-id="'+a.id+'"><div class="blog-card-icon" aria-hidden="true">'+icon(a.cat)+'</div><div class="blog-card-copy"><small>'+cats[a.cat][lang()==='en'?1:0]+' · '+a.min+' '+tx('دقیقه','min')+'</small><h2>'+esc(c.title)+'</h2><p>'+esc(c.desc)+'</p></div><button type="button" class="blog-open" data-blog-open="'+a.id+'">'+tx('خواندن','Read')+' <span aria-hidden="true">←</span></button></article>'}
function visible(){const q=query.trim().toLocaleLowerCase(lang()==='en'?'en':'fa');return articles.filter(a=>{if(filter!=='all'&&a.cat!==filter)return false;if(!q)return true;const c=a[lang()];return (c.title+' '+c.desc+' '+c.body.join(' ')).toLocaleLowerCase(lang()==='en'?'en':'fa').includes(q)})}
function render(){
 const host=$('#elara-blog-view');if(!host)return;
 const rows=visible();
 host.innerHTML='<section class="blog-hero"><div><small>ELARA · JOURNAL</small><h1>'+tx('مجلهٔ الارا','Elara Journal')+'</h1><p>'+tx('ایده‌های کاربردی برای برنامه‌ریزی، تمرکز، عادت و مطالعه؛ کوتاه، روشن و قابل اجرا.','Practical ideas for planning, focus, habits and reading—short, clear and actionable.')+'</p></div><div class="blog-hero-orbit" aria-hidden="true">✦</div></section><section class="blog-toolbar"><label class="blog-search"><span aria-hidden="true">⌕</span><input data-blog-search value="'+esc(query)+'" placeholder="'+tx('جستجو در مقاله‌ها…','Search articles…')+'"></label><div class="blog-cats">'+Object.entries(cats).map(([k,v])=>'<button type="button" data-blog-filter="'+k+'" class="'+(filter===k?'is-active':'')+'">'+v[lang()==='en'?1:0]+'</button>').join('')+'</div></section><section class="blog-grid">'+(rows.map(card).join('')||'<p class="blog-empty">'+tx('چیزی با این جستجو پیدا نشد.','Nothing matched this search.')+'</p>')+'</section><section class="blog-ai-gate"><div><small>ELARA AI TUTOR</small><h2>'+tx('معلم هوشمند داخل مقاله — در راه','AI tutor inside articles — coming later')+'</h2><p>'+tx('این قابلیت فقط وقتی فعال می‌شود که gateway امن سمت سرور، محدودیت مصرف و provenance آماده باشد؛ هیچ کلید API داخل مرورگر قرار نمی‌گیرد.','This will only activate after a secure server-side gateway, rate limits and provenance are ready; no API key will live in the browser.')+'</p></div><span aria-hidden="true">✧</span></section>';
}
async function openArticle(id){const a=articles.find(x=>x.id===id);if(!a)return;const c=a[lang()],wrap=document.createElement('article');wrap.className='blog-article-detail';wrap.innerHTML='<header><small>'+cats[a.cat][lang()==='en'?1:0]+' · '+a.min+' '+tx('دقیقه','min')+'</small><h2>'+esc(c.title)+'</h2><p>'+esc(c.desc)+'</p></header>'+c.body.map((p,i)=>'<section><b>'+(i+1)+'</b><p>'+esc(p)+'</p></section>').join('')+'<footer><button type="button" class="primary-button" data-blog-go-tasks>'+tx('رفتن به تسک‌ها','Go to Tasks')+'</button></footer>';await window.ElaraDialog.open({title:tx('مقالهٔ الارا','Elara article'),content:wrap,wide:true,actions:[{label:tx('بستن','Close'),value:false}]})}
document.addEventListener('click',e=>{const f=e.target.closest('[data-blog-filter]');if(f){filter=f.dataset.blogFilter;render();return}const o=e.target.closest('[data-blog-open]');if(o){openArticle(o.dataset.blogOpen);return}if(e.target.closest('[data-blog-go-tasks]')){window.ElaraDialog.close();window.ElaraOpen?.('tasks')}});
document.addEventListener('input',e=>{if(e.target.matches('[data-blog-search]')){query=e.target.value;render()}});
for(const ev of ['elara:locale-changed','elara:open'])window.addEventListener(ev,e=>{if(ev==='elara:open'&&e.detail?.tab!=='blog')return;setTimeout(render,0)});
const start=()=>{render();if(location.hash==='#blog')setTimeout(render,50)};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
window.ElaraBlog={articles,render,openArticle};
})();