/* Persian calendar UI; stores Gregorian ISO keys used by the existing data model. */
(()=>{'use strict';
const S=window.ElaraSchedule,parts=d=>Object.fromEntries(new Intl.DateTimeFormat('en-u-ca-persian',{year:'numeric',month:'numeric',day:'numeric'}).formatToParts(d).map(x=>[x.type,Number(x.value)]));
function open(value,onSelect){let cursor=new Date((S.validDate(value)?value:S.today())+'T12:00:00');const wrap=document.createElement('div');wrap.className='elara-calendar';wrap.dir='rtl';
function paint(){const p=parts(cursor),start=new Date(cursor);start.setDate(start.getDate()-p.day+1);const next=new Date(start);next.setDate(next.getDate()+32);next.setDate(next.getDate()-parts(next).day+1);const length=Math.round((next-start)/86400000),offset=(start.getDay()+1)%7;
wrap.innerHTML=`<header><button type="button" data-month="-1" aria-label="ماه قبل">‹</button><strong>${cursor.toLocaleDateString('fa-IR',{month:'long',year:'numeric'})}</strong><button type="button" data-month="1" aria-label="ماه بعد">›</button></header><div class="calendar-grid" role="group" aria-label="روزهای ماه">${['ش','ی','د','س','چ','پ','ج'].map(x=>'<span>'+x+'</span>').join('')}${'<span></span>'.repeat(offset)}${Array.from({length},(_,i)=>{const d=new Date(start);d.setDate(d.getDate()+i);const key=S.iso(d);return `<button type="button" data-day="${key}" aria-pressed="${key===value}" ${key===S.today()?'aria-current="date"':''}>${(i+1).toLocaleString('fa-IR')}</button>`}).join('')}</div><button type="button" class="quiet-button" data-day="${S.today()}">امروز</button>`;
wrap.querySelector('[data-month="-1"]').onclick=()=>{cursor=new Date(start);cursor.setDate(cursor.getDate()-1);paint()};wrap.querySelector('[data-month="1"]').onclick=()=>{cursor=next;paint()};wrap.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{onSelect(b.dataset.day);window.ElaraDialog.close()});}
wrap.addEventListener('keydown',e=>{const b=e.target.closest('[data-day]');if(!b)return;const shifts={ArrowLeft:1,ArrowRight:-1,ArrowDown:7,ArrowUp:-7};if(!(e.key in shifts))return;e.preventDefault();const d=new Date(b.dataset.day+'T12:00:00');d.setDate(d.getDate()+shifts[e.key]);cursor=d;paint();wrap.querySelector(`[data-day="${S.iso(d)}"]`)?.focus()});paint();void window.ElaraDialog.open({title:'انتخاب تاریخ',content:wrap,actions:[{label:'بستن',value:false}]});}
window.ElaraCalendar={open};
})();
