(()=>{'use strict';
const PREFIX='elara_collection_v1_',uid=()=>window.ElaraAccount?.user?.uid||window.ElaraSocial?.me?.uid||'guest',key=(id=uid())=>PREFIX+String(id||'guest');
function read(id=uid()){try{const r=JSON.parse(localStorage.getItem(key(id))||'{}');return{owned:Array.isArray(r.owned)?[...new Set(r.owned.map(String))].slice(0,5000):[]}}catch{return{owned:[]}}}
function write(v,id=uid()){const n={owned:[...new Set((v?.owned||[]).map(String))].slice(0,5000)};localStorage.setItem(key(id),JSON.stringify(n));return n}
function counts(){try{const s=JSON.parse(localStorage.getItem('elara_space_v1')||'{}');return{totalDone:new Set((s.taskCompletionHistory||[]).map(x=>x.taskId+'|'+x.date)).size||(s.tasks||[]).filter(x=>x.completed).length,words:(s.words||[]).length,books:(s.books||[]).filter(x=>x.shelf==='finished').length}}catch{return{totalDone:0,words:0,books:0}}}
function xp(){try{const s=JSON.parse(localStorage.getItem('elara_space_v1')||'{}');return Number(window.ElaraSocial?.me?.xp??s.xp??0)||0}catch{return Number(window.ElaraSocial?.me?.xp||0)||0}}
function automaticIds(){const value=xp(),lv=window.ElaraLevels?.level?.(value)||1,ids=[];for(let n=1;n<=Math.min(10,lv);n++)ids.push('avatar:male:'+n,'avatar:female:'+n);for(const [id,min] of [['bronze',1],['silver',4],['gold',7],['diamond',10]])if(lv>=min)ids.push('frame:'+id);for(const [id,min] of [['moon',1],['dream',4],['castle',8],['dawn',10]])if(lv>=min)ids.push('banner:'+id);for(const m of window.ElaraLevels?.medals?.(counts(),value)||[])if(m.earned)ids.push('medal:'+m.id);return ids}
function snapshot(state=read()){const owned=state.owned||[],medals=owned.filter(x=>x.startsWith('medal:')).length,cosmetics=owned.length-medals,score=cosmetics+medals*2,level=1+Math.floor(score/6);return{level,score,nextScore:level*6,progress:Math.max(0,Math.min(100,(score-(level-1)*6)/6*100)),owned:owned.slice(),cosmetics,medals}}
function sync(){const state=read(),owned=[...new Set([...state.owned,...automaticIds()])],next=owned.length===state.owned.length?state:write({owned}),snap=snapshot(next);window.dispatchEvent(new CustomEvent('elara:collection-updated',{detail:snap}));return snap}
function registerOwned(ids,{source='unlock'}={}){if(!['unlock','event','shop'].includes(source))throw Error('invalid collection source');const state=read(),items=(Array.isArray(ids)?ids:[ids]).map(String).filter(x=>/^(?:avatar|frame|banner|medal|cosmetic|theme|pet):[a-z0-9:_-]{1,120}$/i.test(x));const snap=snapshot(write({owned:[...state.owned,...items]}));window.dispatchEvent(new CustomEvent('elara:collection-updated',{detail:snap}));return snap}
for(const ev of ['elara:account-ready','elara:data-changed','elara:wardrobe-changed','elara:levels-ready'])window.addEventListener(ev,()=>setTimeout(sync,0));if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',sync,{once:true});else sync();
window.ElaraCollection={PREFIX,key,read,sync,snapshot,registerOwned,counts};
})();