/* Firestore-backed friendships and opt-in activity summaries. No synthetic profiles, statuses or rankings. */
import {getApp} from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js';
import {getAuth,onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js';
import {getFirestore,doc,getDoc,collection,getDocs,query,where,updateDoc,setDoc,deleteDoc,serverTimestamp} from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js';
const auth=getAuth(getApp()),db=getFirestore(getApp()),$=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={me:null,friends:[],requests:[],activities:[],error:''};window.ElaraSocial=state;
const lv=x=>window.ElaraLevels?.level(x)||1,title=x=>window.ElaraLevels?.title(x)||'جوینده';
let uid=null,baseline=null,busy=false,rerun=false,generation=0;
function avatar(name){return `<span class="elara-social-avatar" aria-hidden="true">${esc((name||'E').trim().slice(0,1).toUpperCase())}</span>`}
function profile(p){return `<span class="elara-social-info"><strong>${esc(p.name||p.username||'کاربر')}</strong><small>@${esc(p.username||'')} · ${esc(title(p.xp))} · Lv.${lv(p.xp)}</small></span>`}
function inform(value){state.error=value;window.dispatchEvent(new Event('elara:social-updated'))}
async function obtain(){const user=auth.currentUser;if(!user?.emailVerified)return false;const result=await getDoc(doc(db,'profiles',user.uid));if(!result.exists())return false;state.me={uid:user.uid,...result.data()};uid=user.uid;return true}
async function refresh(){if(busy){rerun=true;return}if(!(await obtain()))return;busy=true;const mine=uid,gen=++generation;try{
 const [incoming,outgoing]=await Promise.all(['to','from'].map(field=>getDocs(query(collection(db,'friendRequests'),where(field,'==',mine)))));
 if(auth.currentUser?.uid!==mine)return;
 const entries=new Map([...incoming.docs,...outgoing.docs].map(s=>[s.id,{id:s.id,...s.data()}]));
 const enriched=[];for(const request of entries.values()){const other=request.from===mine?request.to:request.from,p=await getDoc(doc(db,'profiles',other));if(p.exists())enriched.push({...request,other,person:{uid:other,...p.data()}})}
 if(auth.currentUser?.uid!==mine)return;
 state.requests=enriched;state.friends=enriched.filter(r=>r.status==='accepted').map(r=>r.person).filter((p,i,a)=>a.findIndex(v=>v.uid===p.uid)===i);
 const recent=[];for(const friend of state.friends.slice(0,12)){const docs=await getDocs(query(collection(db,'activities'),where('uid','==',friend.uid)));for(const event of docs.docs){const a=event.data();recent.push({id:event.id,person:friend,...a,ms:a.createdAt?.toMillis?.()||0})}}
 if(auth.currentUser?.uid!==mine)return;state.activities=recent.sort((a,b)=>b.ms-a.ms).slice(0,30);state.error='';if(gen===generation)render();
 }catch(error){console.error('Elara friends:',error);state.error=error.code==='permission-denied'?'قوانین فعالیت دوستان باید در Firestore Rules منتشر شوند.':error.message||'خطا در دریافت اطلاعات دوستان';render()}finally{busy=false;if(rerun){rerun=false;void refresh()}}}
window.ElaraSocial.refresh=refresh;
async function addFriend(value){if(!state.me)throw Error('ابتدا وارد حساب شو.');const username=String(value||'').trim().replace(/^@/,'').toLowerCase();if(!/^[a-z][a-z0-9_]{2,19}$/.test(username))throw Error('نام کاربری انگلیسی معتبر وارد کن.');const claim=await getDoc(doc(db,'usernames',username));if(!claim.exists())throw Error('این نام کاربری پیدا نشد.');const to=claim.data().uid;if(to===uid)throw Error('نمی‌توانی خودت را به دوستانت اضافه کنی.');const known=state.requests.find(r=>r.other===to&&r.status!=='declined');if(known)throw Error(known.status==='accepted'?'قبلاً دوست شده‌اید.':'درخواست شما هنوز در جریان است.');await setDoc(doc(db,'friendRequests',uid+'_'+to),{from:uid,to,status:'pending'});await refresh()}
async function decide(request,status){if(request.to!==uid||request.status!=='pending')throw Error('درخواست معتبر نیست.');await updateDoc(doc(db,'friendRequests',request.id),{status});await refresh()}
function render(){if(!$('elara-social-page'))return;const incoming=state.requests.filter(r=>r.to===uid&&r.status==='pending'),outgoing=state.requests.filter(r=>r.from===uid&&r.status==='pending');const requests=incoming.map(r=>`<div class="elara-item">${avatar(r.person.name)}${profile(r.person)}<button type="button" class="primary-button" data-friend-action="accept" data-request="${esc(r.id)}">قبول</button><button type="button" class="quiet-button" data-friend-action="decline" data-request="${esc(r.id)}">رد</button></div>`).join('')||'<p class="muted">درخواست دریافتی نداری.</p>';const friends=state.friends.map(p=>`<div class="elara-item">${avatar(p.name)}${profile(p)}<span class="muted">${Number(p.xp||0).toLocaleString('fa-IR')} XP</span></div>`).join('')||'<p class="muted">هنوز دوستی تأیید نشده است.</p>';const activities=state.activities.map(a=>`<div class="elara-item">${avatar(a.person.name)}<span class="elara-social-info"><strong>${esc(a.person.name||a.person.username)}</strong><small>${a.type==='task'?'یک کار را تکمیل کرد':'یک عادت روزانه را انجام داد'} · ${a.ms?new Date(a.ms).toLocaleString('fa-IR'):'همین حالا'}</small></span></div>`).join('')||'<p class="muted">هنوز فعالیت اشتراک‌گذاری‌شده‌ای ثبت نشده است.</p>';
$('elara-social-page').innerHTML=`<div class="elara-stats"><div class="elara-stat"><strong>${state.friends.length}</strong><small>دوست تأییدشده</small></div><div class="elara-stat"><strong>${incoming.length}</strong><small>درخواست دریافتی</small></div><div class="elara-stat"><strong>${outgoing.length}</strong><small>در انتظار پذیرش</small></div></div><div class="elara-social-grid"><section class="elara-card wide"><h2>افزودن دوست با نام کاربری یکتا</h2><form class="inline-form" id="elara-add-friend"><input id="elara-add-friend-name" required pattern="[a-z][a-z0-9_]{2,19}" placeholder="username" aria-label="نام کاربری انگلیسی دوست"><button type="submit" class="primary-button">ارسال درخواست</button><button type="button" class="quiet-button" data-social-refresh>به‌روزرسانی</button></form><p id="elara-social-message" class="elara-message">${esc(state.error)}</p></section><section class="elara-card"><h2>درخواست‌های دوستی</h2>${requests}</section><section class="elara-card"><h2>دوستان من</h2>${friends}</section><section class="elara-card wide"><h2>فعالیت واقعی دوستان</h2><p class="muted">فقط خلاصهٔ فعالیت‌هایی که دوستت با رضایت به اشتراک گذاشته؛ عنوان خصوصی کارها نمایش داده نمی‌شود.</p>${activities}</section></div>`;
const self=state.me?{...state.me,xp:Number(state.me.xp)||0}:null,ranking=[self,...state.friends].filter(Boolean).sort((a,b)=>(Number(b.xp)||0)-(Number(a.xp)||0));const lines=ranking.map((p,i)=>`<div class="elara-rank-line"><b>${i+1}</b>${avatar(p.name)}${profile(p)}<span>${Number(p.xp||0).toLocaleString('fa-IR')} XP</span></div>`).join('');$('elara-ranking-page').innerHTML=`<div class="elara-social-grid"><section class="elara-card wide"><h2>رنکینگ میان من و دوستان پذیرفته‌شده</h2><p class="muted">سطح، لقب و XP از پروفایل‌های Firestore خوانده می‌شوند؛ XP سمت مرورگر ضدتقلب نیست.</p>${lines||'<p class="muted">هنوز حسابی بارگذاری نشده است.</p>'}<button type="button" class="quiet-button" data-social-refresh>به‌روزرسانی</button></section><section class="elara-card wide"><h2>لقب‌های مسیر (۱۰ سطح)</h2><div class="elara-title-grid">${window.ElaraLevels?.titles.map((t,i)=>`<span class="elara-title-pill">${i+1>lv(self?.xp)?'🔒':'✦'} ${i+1} · ${esc(t)}</span>`).join('')||''}</div></section></div>`;$('elara-home-activity').innerHTML=state.activities.slice(0,4).map(a=>`<div class="elara-item">${avatar(a.person.name)}<span class="elara-social-info"><strong>${esc(a.person.name||a.person.username)}</strong><small>${a.type==='task'?'یک کار را تکمیل کرد':'یک عادت را انجام داد'}</small></span></div>`).join('')||'<p class="muted">دوستانت باید اشتراک‌گذاری خلاصه فعالیت را فعال کنند.</p>';$('elara-home-social').innerHTML=`<p>${state.friends.length} دوست تأییدشده · ${incoming.length} درخواست جدید</p><button type="button" data-elara-tab="social" class="primary-button">مشاهده دوستان و درخواست‌ها</button>`;$('elara-home-ranks').innerHTML=lines||'<p class="muted">هنوز رتبه‌ای ثبت نشده است.</p>';window.dispatchEvent(new Event('elara:social-updated'))}
// A real event is published only after the user chooses to share; private titles are not included.
async function publish(type){if(!uid||localStorage.getItem('elara_share_activity_'+uid)!=='yes'||!auth.currentUser?.emailVerified)return;const id=uid+'_'+crypto.randomUUID();try{await setDoc(doc(db,'activities',id),{uid,type,eventKey:id,createdAt:serverTimestamp()})}catch(error){console.warn('Activity sharing failed:',error);inform('ثبت فعالیت برای دوستان ناموفق بود: '+(error.code||error.message))}}
function changed(){if(!uid||!state.me)return;let now;try{now=JSON.parse(localStorage.getItem('elara_space_v1')||'{}')}catch{return}if(!baseline){baseline=now;return}const day=new Date(),date=`${day.getFullYear()}-${String(day.getMonth()+1).padStart(2,'0')}-${String(day.getDate()).padStart(2,'0')}`,beforeTasks=new Map((baseline.tasks||[]).map(x=>[x.id,x]));for(const task of now.tasks||[])if(task.completed&&!beforeTasks.get(task.id)?.completed&&task.doneAt===date)void publish('task');const beforeHabits=new Map((baseline.habits||[]).map(x=>[x.id,x]));for(const habit of now.habits||[])if((habit.days||[]).includes(date)&&!(beforeHabits.get(habit.id)?.days||[]).includes(date))void publish('habit');baseline=now}
window.addEventListener('elara:hydrate',e=>{baseline=e.detail||{};setTimeout(refresh,500)});window.addEventListener('elara:data-changed',changed);
document.addEventListener('click',async e=>{if(e.target.id!=='elara-delete-activity')return;const b=e.target;b.disabled=true;try{if(!uid)throw Error('وارد حساب نشده‌ای.');const docs=await getDocs(query(collection(db,'activities'),where('uid','==',uid)));for(const a of docs.docs)await deleteDoc(a.ref);$('elara-delete-activity-status').textContent='فعالیت‌های قبلی پاک شدند.';await refresh()}catch(error){$('elara-delete-activity-status').textContent=error.message||String(error)}finally{b.disabled=false}});
document.addEventListener('submit',async e=>{if(e.target.id!=='elara-add-friend')return;e.preventDefault();const button=e.target.querySelector('[type=submit]');button.disabled=true;try{await addFriend($('elara-add-friend-name').value);e.target.reset();$('elara-social-message').textContent='درخواست فرستاده شد.'}catch(error){$('elara-social-message').textContent=error.message||String(error)}finally{button.disabled=false}});
document.addEventListener('click',async e=>{const b=e.target.closest('[data-friend-action],[data-social-refresh]');if(!b)return;if(b.hasAttribute('data-social-refresh')){void refresh();return}const req=state.requests.find(r=>r.id===b.dataset.request);if(!req)return;b.disabled=true;try{await decide(req,b.dataset.friendAction==='accept'?'accepted':'declined')}catch(error){inform(error.message||String(error))}finally{b.disabled=false}});
onAuthStateChanged(auth,async user=>{uid=null;state.me=null;state.friends=[];state.requests=[];state.activities=[];baseline=null;if(!user){render();return}if(user.emailVerified){try{if(await obtain()){baseline=JSON.parse(localStorage.getItem('elara_space_v1')||'{}');await refresh()}}catch(error){console.error('Social auth:',error)}}});