/* Freedom AI client. Provider/model internals stay server-side; only Elara display names are rendered here. */
(()=>{'use strict';
const host=()=>document.querySelector('#panel-freedom [data-f-ai-host]'),uid=()=>window.ElaraAccount?.user?.uid||'guest',key=()=>'elara_freedom_ai_chat_v1_'+uid();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=()=>{try{const x=JSON.parse(localStorage.getItem(key())||'[]');return Array.isArray(x)?x.slice(-30):[]}catch{return[]}};
const write=rows=>localStorage.setItem(key(),JSON.stringify(rows.slice(-30)));
function render(){const h=host();if(!h)return;const rows=read(),signed=!!window.ElaraAccount?.user;h.innerHTML='<div class="freedom-ai-thread">'+(rows.length?rows.map(r=>'<article class="freedom-ai-message '+(r.role==='model'?'model':'user')+'"><small>'+esc(r.role==='model'?(r.name||'Elara AI'):'تو')+'</small><p dir="auto">'+esc(r.text)+'</p></article>').join(''):'<div class="freedom-ai-empty"><strong>Elara AI</strong><span>ایده‌ات را بنویس؛ پاسخ فقط وقتی ارسال می‌شود که خودت دکمهٔ ارسال را بزنی.</span></div>')+'</div><form class="freedom-ai-form" data-f-ai-form><textarea name="message" rows="2" maxlength="8000" placeholder="'+(signed?'با Elara حرف بزن…':'برای استفاده از AI وارد حساب شو')+'" '+(signed?'':'disabled')+'></textarea><div><button type="button" class="quiet-button" data-f-ai-clear '+(rows.length?'':'disabled')+'>پاک‌کردن گفتگو</button><button type="submit" class="freedom-neon-button" '+(signed?'':'disabled')+'>ارسال</button></div></form><p class="freedom-ai-status" data-f-ai-status></p>';const thread=h.querySelector('.freedom-ai-thread');if(thread)thread.scrollTop=thread.scrollHeight}
async function submit(form){const user=window.ElaraAccount?.user;if(!user)return;const input=form.elements.message,message=String(input.value||'').trim();if(!message)return;const button=form.querySelector('[type=submit]'),status=host()?.querySelector('[data-f-ai-status]'),before=read();button.disabled=true;input.disabled=true;if(status)status.textContent='Elara در حال فکر کردن…';const next=[...before,{role:'user',text:message,at:Date.now()}];write(next);render();try{const token=await user.getIdToken(),history=before.slice(-10).map(x=>({role:x.role,text:x.text})),response=await fetch('ai.php',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token,'Accept':'application/json'},cache:'no-store',credentials:'same-origin',body:JSON.stringify({message,history})}),raw=await response.text();let payload=null;try{payload=JSON.parse(raw)}catch{throw new Error('AI backend روی این محیط فعال نیست.')}if(!response.ok||payload?.ok!==true)throw new Error(payload?.error||('AI HTTP '+response.status));const data=payload.data||{};write([...next,{role:'model',text:String(data.text||'').trim(),name:data.display_name||'Elara AI',at:Date.now()}]);render()}catch(error){write(before);render();const s=host()?.querySelector('[data-f-ai-status]');if(s)s.textContent=error.message||'پاسخ AI در دسترس نیست.'}finally{const f=host()?.querySelector('[data-f-ai-form]');if(f){f.elements.message.disabled=false;f.querySelector('[type=submit]').disabled=false;f.elements.message.value='';f.elements.message.focus()}}}
document.addEventListener('submit',e=>{if(!e.target.matches?.('[data-f-ai-form]'))return;e.preventDefault();submit(e.target)},true);
document.addEventListener('click',e=>{if(!e.target.closest?.('[data-f-ai-clear]'))return;if(confirm('گفتگوی محلی Elara AI پاک شود؟')){localStorage.removeItem(key());render()}},true);
for(const n of ['elara:freedom-rendered','elara:account-ready','elara:logout'])window.addEventListener(n,()=>setTimeout(render,0));
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',()=>setTimeout(render,0),{once:true}):setTimeout(render,0);
window.ElaraFreedomAI={render};
})();