(()=>{'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const t=(fa,en)=>window.ElaraI18n?.t?.(fa,en)||(document.documentElement.lang==='en'?en:fa);
const num=n=>Number(n||0).toLocaleString(document.documentElement.lang==='en'?'en-US':'fa-IR');
function ago(ms){const d=Math.max(0,Date.now()-(Number(ms)||Date.now())),m=Math.floor(d/60000);if(m<1)return t('الان','now');if(m<60)return num(m)+' '+t('دقیقه پیش','min ago');const h=Math.floor(m/60);if(h<24)return num(h)+' '+t('ساعت پیش','h ago');return num(Math.floor(h/24))+' '+t('روز پیش','d ago')}
function avatar(p){const model=window.ElaraProfileSystem?.viewModel?.(p,{self:p?.uid===window.ElaraAccount?.user?.uid});const src=model?.avatarSrc;return src?'<img src="'+esc(src)+'" alt="">':'<span>'+esc((p?.name||p?.username||'?').slice(0,1))+'</span>'}
function vis(v){return v==='private'?t('خصوصی','Private'):v==='public'?t('عمومی','Public'):t('دوستان','Friends')}
function engage(id){return id?'<div class="social-engagement-bar page-engagement" data-engagement-kind="post" data-engagement-id="'+esc(id)+'"><button type="button" data-engagement-like aria-pressed="false"><span data-engagement-heart>♡</span><span data-engagement-like-count>0</span></button><button type="button" data-engagement-comment>💬 <span data-engagement-comment-count>0</span></button></div>':''}
function postActions(p,uid){
 if(p.uid===uid)return '<div class="page-post-actions"><button type="button" data-page-edit-post="'+esc(p.id)+'">'+t('ویرایش','Edit')+'</button><button type="button" class="danger" data-page-delete-post="'+esc(p.id)+'">'+t('حذف','Delete')+'</button></div>';
 return '<div class="page-post-actions"><button type="button" data-page-report-post="'+esc(p.id)+'">'+t('گزارش','Report')+'</button><button type="button" class="danger-outline" data-page-block-post="'+esc(p.id)+'">'+t('مسدود','Block')+'</button></div>'
}
function reasonOptions(){return [['spam',t('اسپم','Spam')],['harassment',t('آزار و اذیت','Harassment')],['hate',t('نفرت‌پراکنی','Hate')],['sexual',t('محتوای جنسی','Sexual content')],['violence',t('خشونت','Violence')],['privacy',t('نقض حریم خصوصی','Privacy')],['other',t('سایر','Other')]].map(([v,l])=>'<option value="'+v+'">'+l+'</option>').join('')}
async function editPost(row){
 const form=document.createElement('form');form.className='page-edit-form';form.innerHTML='<label>'+t('متن پست','Post text')+'<textarea name="text" maxlength="4000" data-elara-ugc dir="auto" required>'+esc(row.text||'')+'</textarea></label><label>'+t('نمایش','Visibility')+'<select name="visibility"><option value="friends" '+(row.visibility==='friends'?'selected':'')+'>'+t('دوستان','Friends')+'</option><option value="public" '+(row.visibility==='public'?'selected':'')+'>'+t('عمومی','Public')+'</option><option value="private" '+(row.visibility==='private'?'selected':'')+'>'+t('خصوصی','Private')+'</option></select></label>';
 const ok=await window.ElaraDialog.open({title:t('ویرایش پست','Edit post'),content:form,actions:[{label:t('انصراف','Cancel'),value:false},{label:t('ذخیره تغییرات','Save changes'),value:true,kind:'primary'}]});if(ok!==true)return;
 await window.ElaraPage?.editPost?.(row.id,form.elements.text.value,form.elements.visibility.value)
}
async function report(kind,row){
 const form=document.createElement('form');form.className='page-report-form';form.innerHTML='<label>'+t('دلیل گزارش','Report reason')+'<select name="reason">'+reasonOptions()+'</select></label><label>'+t('توضیح اختیاری','Optional details')+'<textarea name="detail" maxlength="500" data-elara-ugc dir="auto" placeholder="'+t('اگر لازم است توضیح کوتاهی بنویس…','Add a short note if needed…')+'"></textarea></label><p class="muted">'+t('گزارش برای بررسی ثبت می‌شود و به صاحب محتوا نمایش داده نمی‌شود.','Your report is private and is not shown to the content owner.')+'</p>';
 const ok=await window.ElaraDialog.open({title:t('گزارش محتوا','Report content'),content:form,actions:[{label:t('انصراف','Cancel'),value:false},{label:t('ثبت گزارش','Submit report'),value:true,kind:'danger'}]});if(ok!==true)return;
 const result=await window.ElaraPage?.reportContent?.(kind,row.id,form.elements.reason.value,form.elements.detail.value);
 await window.ElaraDialog.alert(result==='existing'?t('این محتوا را قبلاً گزارش کرده‌ای.','You already reported this content.'):t('گزارش ثبت شد. ممنون که کمک می‌کنی فضا سالم بماند.','Report submitted. Thanks for helping keep the space safe.'),{title:t('گزارش','Report')})
}
async function block(row){
 if(!row?.uid)return;const ok=await window.ElaraDialog.confirm(t('این کاربر مسدود شود؟ دوستی و دسترسی اجتماعی بین شما قطع می‌شود.','Block this user? Your friendship and social access will be removed.'),{title:t('مسدودکردن کاربر','Block user'),danger:true,confirmText:t('مسدودکردن','Block')});if(!ok)return;
 await window.ElaraSocial?.blockUser?.(row.uid,row.person||{});await window.ElaraPage?.refresh?.();render()
}
function injectFriendsCta(){const head=document.querySelector('#elara-social-page .social-page-head');if(!head||head.querySelector('[data-elara-page-cta]'))return;const b=document.createElement('button');b.type='button';b.className='quiet-button social-page-cta';b.dataset.elaraPageCta='';b.dataset.elaraTab='page';b.textContent=t('پیج و استاتوس','Page & Status');head.append(b)}
function render(){
 const root=document.getElementById('elara-page-view');if(!root)return;root.dataset.elaraI18n='off';
 const api=window.ElaraPage,state=api?.state||{posts:[],stories:[],loading:false,error:''},uid=window.ElaraAccount?.user?.uid||window.ElaraSocial?.me?.uid;
 const stories=(state.stories||[]).map(s=>'<button type="button" class="page-story" data-page-story="'+esc(s.id)+'"><span class="page-story-ring">'+avatar(s.person)+'</span><strong>'+esc(s.person?.name||s.person?.username||t('دوست','Friend'))+'</strong><small>'+ago(s.createdMs)+'</small></button>').join('');
 const posts=(state.posts||[]).map(p=>'<article class="page-post" data-page-post-id="'+esc(p.id)+'"><header><span class="page-post-avatar">'+avatar(p.person)+'</span><div><strong>'+esc(p.person?.name||p.person?.username||t('دوست','Friend'))+'</strong><small>'+ago(p.createdMs)+' · '+vis(p.visibility)+'</small></div>'+postActions(p,uid)+'</header><p data-elara-ugc dir="auto">'+esc(p.text||'')+'</p>'+engage(p.id)+'</article>').join('');
 root.innerHTML='<section class="page-hero"><div><small>ELARA · PAGE</small><h1>'+t('پیج من','My Page')+'</h1><p>'+t('جایی برای پست‌ها و استاتوس‌های تو و دوستات.','A space for your posts and your friends’ statuses.')+'</p></div><div class="page-hero-note">'+t('رسانهٔ عمومی بعد از فعال‌شدن Storage امن اضافه می‌شود.','Public media will be added after secure Storage is enabled.')+'</div></section><section class="page-compose-grid"><form class="elara-card page-story-compose" data-page-story-form><h2>'+t('استاتوس ۲۴ ساعته','24-hour status')+'</h2><textarea name="text" maxlength="1000" data-elara-ugc dir="auto" placeholder="'+t('الان چه حسی داری؟','What’s your vibe right now?')+'" required></textarea><div><select name="visibility"><option value="friends">'+t('دوستان','Friends')+'</option><option value="public">'+t('عمومی','Public')+'</option><option value="private">'+t('خصوصی','Private')+'</option></select><button class="primary-button" type="submit">'+t('گذاشتن استاتوس','Post status')+'</button></div></form><form class="elara-card page-post-compose" data-page-post-form><h2>'+t('پست جدید','New post')+'</h2><textarea name="text" maxlength="4000" data-elara-ugc dir="auto" placeholder="'+t('چی می‌خوای با دوستات به اشتراک بذاری؟','What do you want to share?')+'" required></textarea><div><select name="visibility"><option value="friends">'+t('دوستان','Friends')+'</option><option value="public">'+t('عمومی','Public')+'</option><option value="private">'+t('خصوصی','Private')+'</option></select><button class="primary-button" type="submit">'+t('انتشار پست','Publish post')+'</button></div></form></section><section class="elara-card page-stories"><header><h2>'+t('استاتوس‌ها','Statuses')+'</h2><small>'+t('بعد از ۲۴ ساعت برای دیگران نمایش داده نمی‌شوند.','They disappear for others after 24 hours.')+'</small></header><div class="page-story-strip">'+(stories||'<p class="ref-empty">'+t('استاتوسی برای نمایش نیست.','No statuses to show.')+'</p>')+'</div></section><section class="page-feed"><header><h2>'+t('پست‌های من و دوستان','Posts from you & friends')+'</h2><button type="button" class="quiet-button" data-page-refresh>'+t('تازه‌سازی','Refresh')+'</button></header>'+(state.loading?'<p class="ref-empty">'+t('در حال بارگذاری…','Loading…')+'</p>':state.error?'<p class="ref-empty">'+esc(state.error)+'</p>':posts||'<p class="ref-empty">'+t('هنوز پستی نیست.','No posts yet.')+'</p>')+'</section>';
}
async function submit(form,kind){const api=window.ElaraPage;if(!api)return;const button=form.querySelector('button[type=submit]');button.disabled=true;try{if(kind==='story')await api.createStory(form.elements.text.value,form.elements.visibility.value);else await api.createPost(form.elements.text.value,form.elements.visibility.value);form.reset()}catch(error){await window.ElaraDialog?.alert?.(String(error?.message||error),{title:t('انتشار انجام نشد','Could not publish')})}finally{button.disabled=false;render()}}
document.addEventListener('submit',e=>{if(e.target.matches('[data-page-story-form]')){e.preventDefault();void submit(e.target,'story')}else if(e.target.matches('[data-page-post-form]')){e.preventDefault();void submit(e.target,'post')}});
document.addEventListener('click',async e=>{
 if(e.target.closest('[data-page-refresh]')){await window.ElaraPage?.refresh?.();return}
 const del=e.target.closest('[data-page-delete-post]');if(del){if(await window.ElaraDialog.confirm(t('این پست حذف شود؟','Delete this post?'),{title:t('حذف پست','Delete post'),danger:true,confirmText:t('حذف','Delete')}))await window.ElaraPage?.deletePost?.(del.dataset.pageDeletePost);return}
 const edit=e.target.closest('[data-page-edit-post]');if(edit){const row=window.ElaraPage?.state?.posts?.find(x=>x.id===edit.dataset.pageEditPost);if(row)await editPost(row);return}
 const reportPost=e.target.closest('[data-page-report-post]');if(reportPost){const row=window.ElaraPage?.state?.posts?.find(x=>x.id===reportPost.dataset.pageReportPost);if(row)await report('post',row);return}
 const blockPost=e.target.closest('[data-page-block-post]');if(blockPost){const row=window.ElaraPage?.state?.posts?.find(x=>x.id===blockPost.dataset.pageBlockPost);if(row)await block(row);return}
 const story=e.target.closest('[data-page-story]');if(story){const row=window.ElaraPage?.state?.stories?.find(x=>x.id===story.dataset.pageStory);if(!row)return;const box=document.createElement('article');box.className='page-story-detail';box.dataset.elaraI18n='off';box.innerHTML='<span class="page-story-ring">'+avatar(row.person)+'</span><h3>'+esc(row.person?.name||t('دوست','Friend'))+'</h3><p data-elara-ugc dir="auto">'+esc(row.text||'')+'</p><small>'+ago(row.createdMs)+' · '+vis(row.visibility)+'</small>';if(row.uid===(window.ElaraAccount?.user?.uid||window.ElaraSocial?.me?.uid)){const d=document.createElement('button');d.type='button';d.className='page-story-delete danger';d.textContent=t('حذف استاتوس','Delete status');d.onclick=async()=>{await window.ElaraPage?.deleteStory?.(row.id);window.ElaraDialog.close()};box.append(d)}else{const actions=document.createElement('div');actions.className='page-story-moderation';actions.innerHTML='<button type="button" data-page-report-story>'+t('گزارش','Report')+'</button><button type="button" class="danger-outline" data-page-block-story>'+t('مسدود','Block')+'</button>';actions.querySelector('[data-page-report-story]').onclick=async()=>{window.ElaraDialog.close();await report('story',row)};actions.querySelector('[data-page-block-story]').onclick=async()=>{window.ElaraDialog.close();await block(row)};box.append(actions)}await window.ElaraDialog.open({title:t('استاتوس','Status'),content:box,actions:[{label:t('بستن','Close'),value:false}]})}
});
for(const ev of ['elara:page-updated','elara:locale-changed'])window.addEventListener(ev,()=>setTimeout(render,0));
window.addEventListener('elara:open',e=>{if(e.detail?.tab==='page'){render();void window.ElaraPage?.refresh?.()}if(e.detail?.tab==='social')setTimeout(injectFriendsCta,40)});
new MutationObserver(()=>injectFriendsCta()).observe(document.documentElement,{subtree:true,childList:true});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{render();injectFriendsCta()},{once:true});else{render();injectFriendsCta()}
window.ElaraPageView={render};
})();