/* Account-scoped report history. No synthesized or retrospectively inferred values. */
(()=>{'use strict';
const $=id=>document.getElementById(id),S=window.ElaraSchedule,arr=x=>Array.isArray(x)?x:[],esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>window.ElaraAccount?.user?.uid||window.ElaraSocial?.me?.uid||null;
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}};
const key=()=>uid()?'elara_report_history_v1_'+uid():null;
function append(type,value,date=S.today(),id=''){if(!key()||!S.validDate(date)||!Number.isFinite(value))return;const rows=arr(read(key(),[])).filter(r=>!(type==='weight'&&r.type===type&&r.date===date));rows.push({type,value,date,id,at:Date.now()});localStorage.setItem(key(),JSON.stringify(rows.slice(-20000)))}
const metrics=[['reading','صفحات مطالعه','صفحه','#a66eff'],['wordsAdded','واژه‌های افزوده‌شده','واژه','#55baff'],['wordsReviewed','واژه‌های مرورشده','واژه','#e57dab'],['wordsLearned','واژه‌های آموخته‌شده','واژه','#3ce4b0'],['weight','تغییر وزن','کیلوگرم','#b996ff'],['water','مصرف آب','میلی‌لیتر','#49caff'],['sleep','مدت خواب','ساعت','#8f81ff'],['exercise','زمان ورزش','دقیقه','#3ce5b0'],['habits','تکمیل عادت‌ها','نوبت','#e6bd59'],['goals','میانگین پیشرفت اهداف','درصد','#f18eb9']];
let range=7,group='day',lastUid=null,goalSnapshot=null;
function data(){const history=arr(read(key(),[])),wellness=uid()?read('elara_private_wellness_v1_'+uid(),{}):{},state=read('elara_space_v1',{}),series=Object.fromEntries(metrics.map(([id])=>[id,[]]));
for(const row of history)if(series[row.type]&&S.validDate(row.date)&&Number.isFinite(row.value))series[row.type].push(row);
for(const [date,value] of Object.entries(wellness.water||{}))if(S.validDate(date)&&Number.isFinite(Number(value)))series.water.push({date,value:Number(value)});
for(const row of arr(wellness.sleep)){const a=Date.parse(row.date+'T'+row.bed+':00'),b=Date.parse(row.date+'T'+row.wake+':00');if(S.validDate(row.date)&&Number.isFinite(a)&&Number.isFinite(b))series.sleep.push({date:row.date,value:((b<=a?b+86400000:b)-a)/3600000})}
for(const row of arr(wellness.workouts))if(S.validDate(row.date)&&Number.isFinite(Number(row.minutes)))series.exercise.push({date:row.date,value:Number(row.minutes)});
for(const h of arr(state.habits))for(const date of arr(h.days))if(S.validDate(date))series.habits.push({date,value:1});
return series}
function aggregate(rows,type){const end=S.today(),start=new Date(end+'T12:00:00');start.setDate(start.getDate()-range+1);const since=S.iso(start),buckets=new Map();for(const r of rows){if(r.date<since||r.date>end)continue;let date=r.date;if(group==='month')date=date.slice(0,7)+'-01';else if(group==='week'){const d=new Date(date+'T12:00:00');d.setDate(d.getDate()-(d.getDay()+1)%7);date=S.iso(d)}const old=buckets.get(date)||[];old.push(r);buckets.set(date,old)}return [...buckets].sort(([a],[b])=>a.localeCompare(b)).map(([date,values])=>({date,value:type==='weight'?values.reduce((n,r)=>n+r.value,0)/values.length:type==='goals'?values.at(-1).value:values.reduce((n,r)=>n+r.value,0)}))}
function chart(type,title,unit,color,rows){const values=aggregate(rows,type);if(!values.length)return `<article class="elara-card report-chart"><h2>${title}</h2><div class="report-empty">هنوز داده‌ای در این بازه ثبت نشده است.</div></article>`;const max=Math.max(1,...values.map(r=>r.value)),width=560,height=165,step=width/values.length;const bars=values.map((r,i)=>{const h=r.value/max*130,x=i*step+step*.18;return `<rect x="${x}" y="${140-h}" width="${step*.64}" height="${h}" rx="4" fill="${color}"><title>${esc(r.date)}: ${r.value.toLocaleString('fa-IR',{maximumFractionDigits:1})} ${unit}</title></rect>`}).join('');return `<article class="elara-card report-chart"><h2>${title}</h2><svg role="img" aria-label="${title}؛ جزئیات در جدول" viewBox="0 0 ${width} ${height}"><line x1="0" x2="560" y1="141" y2="141" stroke="#52628b"/>${bars}</svg><details><summary>جدول داده‌ها · ${unit}</summary><table><thead><tr><th>تاریخ</th><th>${unit}</th></tr></thead><tbody>${values.map(r=>`<tr><td>${new Date(r.date+'T12:00:00').toLocaleDateString('fa-IR')}</td><td>${r.value.toLocaleString('fa-IR',{maximumFractionDigits:1})}</td></tr>`).join('')}</tbody></table></details></article>`}
function render(){const root=$('elara-reports-page');if(!root)return;root.classList.add('astra-reports');if(!uid()){root.innerHTML='<section class="elara-card"><h2>گزارش‌های شخصی</h2><p>برای مشاهده و ثبت گزارش‌ها وارد حساب شو.</p></section>';return}const series=data();root.innerHTML=`<section class="elara-card reports-toolbar"><p>گزارش‌ها بر اساس ثبت‌های واقعی شما هستند. سابقهٔ جدید مطالعه، واژه و اهداف روی همین دستگاه و جدا برای هر حساب ذخیره می‌شود.</p><label>بازه<select id="report-range">${[7,30,90,365].map(n=>`<option value="${n}" ${n===range?'selected':''}>${n.toLocaleString('fa-IR')} روز</option>`).join('')}</select></label><label>نمایش<select id="report-group"><option value="day" ${group==='day'?'selected':''}>روزانه</option><option value="week" ${group==='week'?'selected':''}>هفتگی</option><option value="month" ${group==='month'?'selected':''}>ماهانه</option></select></label><form id="report-reading-form"><label>تاریخ<input type="date" name="date" required value="${S.today()}" max="${S.today()}"></label><label>صفحات خوانده‌شده<input type="number" name="pages" min="1" max="10000" required></label><button type="submit" class="primary-button">ثبت مطالعه</button></form><p role="status" id="report-status"></p></section>${metrics.map(([id,title,unit,color])=>chart(id,title,unit,color,series[id])).join('')}`;root.querySelector('#report-range').onchange=e=>{range=Number(e.target.value);render()};root.querySelector('#report-group').onchange=e=>{group=e.target.value;render()};root.querySelector('form').onsubmit=e=>{e.preventDefault();const f=e.target,date=f.elements.date.value,pages=Number(f.elements.pages.value);if(!S.validDate(date)||date>S.today()||!Number.isInteger(pages)||pages<1||pages>10000)return;append('reading',pages,date);render();$('report-status').textContent='مطالعه ثبت شد.'}}
function goals(){const current=uid();if(current!==lastUid){lastUid=current;goalSnapshot=null}const rows=arr(read('elara_space_v1',{}).goals),next=new Map(rows.map(g=>[g.id,arr(g.steps).length?Math.round(arr(g.steps).filter(s=>s.done).length/g.steps.length*100):0]));if(current&&goalSnapshot&&next.size){const changed=next.size!==goalSnapshot.size||[...next].some(([id,value])=>goalSnapshot.get(id)!==value);if(changed)append('goals',[...next.values()].reduce((a,b)=>a+b,0)/next.size,S.today(),'all')}goalSnapshot=next}
window.addEventListener('elara:word-added',()=>append('wordsAdded',1));window.addEventListener('elara:word-reviewed',e=>{append('wordsReviewed',1);if(e.detail?.learned)append('wordsLearned',1)});window.addEventListener('elara:wellness-saved',e=>{if(e.detail?.weight!==undefined&&Number(e.detail.weight)>0)append('weight',Number(e.detail.weight))});
window.addEventListener('elara:data-changed',()=>{goals();if(location.hash==='#reports')render()});window.addEventListener('elara:open',e=>{if(e.detail?.tab==='reports')render()});for(const event of ['elara:account-ready','elara:logout','elara:auth-changed'])window.addEventListener(event,()=>{goals();if(location.hash==='#reports')render()});
window.ElaraReports={render,aggregate,data};goals();
})();
