const assert=require('node:assert/strict');const {setup}=require('./dom-check.cjs');
(async()=>{const {dom,w,errors}=await setup();const $=id=>w.document.getElementById(id),tick=()=>new Promise(r=>setTimeout(r,220));const today=w.ElaraSchedule.today(),d=new Date(today+'T12:00:00');d.setDate(d.getDate()-1);const past=w.ElaraSchedule.iso(d);const rule={weekdays:[0,1,2,3,4,5,6],startDate:past,frequency:'daily',interval:1};
let state={version:1,xp:0,tasks:[{id:'single',text:'one-off',date:past,priority:'2'},{id:'daily',text:'recurring',date:past,recurrenceRule:rule}],habits:[{id:'habit',title:'مطالعه',days:[],recurrenceRule:rule}],goals:Array.from({length:7},(_,i)=>({id:'g'+i,title:'هدف '+i,steps:[{id:'s'+i,text:'step',done:false}]}))};
const read=()=>JSON.parse(w.localStorage.getItem('elara_space_v1'));w.localStorage.setItem('elara_space_v1',JSON.stringify(state));w.dispatchEvent(new w.CustomEvent('elara:hydrate',{detail:state}));await tick();w.ElaraReferenceHome.render();assert.equal(w.document.querySelectorAll('[data-ref-task="single"]').length,0);w.document.querySelector(`[data-home-date="${past}"]`).click();assert.equal(w.document.querySelectorAll('[data-ref-task="single"]').length,1);assert.equal(w.document.querySelectorAll('.ref-goal-row').length,7);
w.document.querySelector('[data-ref-task="daily"]').click();await tick();assert.deepEqual(read().tasks.find(t=>t.id==='daily').occurrenceDone,[past]);assert.equal(read().xp,10);w.document.querySelector('[data-ref-task="daily"]').click();await tick();w.document.querySelector('[data-ref-task="daily"]').click();await tick();assert.equal(read().xp,10,'No duplicate XP for same occurrence');w.document.querySelector('[data-ref-habit="habit"]').click();await tick();assert.deepEqual(read().habits[0].days,[past]);assert.equal(read().xp,25);
w.document.querySelector(`[data-home-date="${today}"]`).click();assert.equal(w.document.querySelector('[data-ref-task="daily"]').getAttribute('aria-pressed'),'false');assert.equal(w.document.querySelector('[data-ref-habit="habit"]').getAttribute('aria-pressed'),'false');
// Real composer opened from Home: fields, persistence, recurrence, and draft survival.
w.document.querySelector('[data-home-quick="task"]').click();assert.equal($('task-composer-shell').hidden,false);$('task-title').value='new title';$('task-priority').value='1';$('task-recurrence').checked=true;$('task-recurrence').dispatchEvent(new w.Event('change'));$('task-frequency').value='daily';$('task-interval').value='2';$('task-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await tick();const added=read().tasks.find(t=>t.text==='new title');assert.ok(added);assert.equal(added.priority,'1');assert.equal(added.recurrenceRule.interval,2);assert.equal(added.date,today);
// One Task can require multiple sessions in the same day without duplicating the Task.
w.ElaraTasks.openComposer({date:today});$('task-title').value='two sessions';$('task-daily-target').value='2';$('task-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await tick();let multi=read().tasks.find(t=>t.text==='two sessions');assert.ok(multi);assert.equal(multi.dailyTarget,2);const beforeMultiXp=read().xp;await w.ElaraTasks.taskAction('toggle-task',multi.id);multi=read().tasks.find(t=>t.id===multi.id);assert.equal(multi.dailyProgress[today],1);assert.equal(multi.completed,false);assert.equal(w.ElaraTasks.taskDone(multi,today),false);assert.equal(read().xp,beforeMultiXp);await w.ElaraTasks.taskAction('toggle-task',multi.id);multi=read().tasks.find(t=>t.id===multi.id);assert.equal(multi.dailyProgress[today],2);assert.equal(multi.completed,true);assert.equal(w.ElaraTasks.taskDone(multi,today),true);assert.equal(read().xp,beforeMultiXp+10);await w.ElaraTasks.taskAction('toggle-task',multi.id);multi=read().tasks.find(t=>t.id===multi.id);assert.equal(multi.dailyProgress[today],1);assert.equal(multi.completed,false);assert.equal(read().xp,beforeMultiXp+10,'multi-session undo must not duplicate XP');
// Grouped Task view reuses the same Tasks and can switch between Folder and Priority without duplicating data.
const groupButton=w.document.querySelector('[data-task-view="group"]');assert.ok(groupButton,'grouped Task view button missing');groupButton.click();await tick();assert.equal($('panel-tasks').dataset.taskView,'group');assert.equal($('task-group-by').hidden,false);assert.ok(w.document.querySelectorAll('#task-list>.astra-task-group-card').length>=1,'grouped Task cards did not render');$('task-group-by').value='priority';$('task-group-by').dispatchEvent(new w.Event('change',{bubbles:true}));await tick();assert.ok([...w.document.querySelectorAll('.astra-task-group-card>header strong')].some(x=>/P[1-4]/.test(x.textContent)),'priority Task groups did not render');assert.equal(read().tasks.filter(t=>t.text==='two sessions').length,1,'group view duplicated Task data');
w.ElaraTasks.openComposer({date:today});$('task-title').value='saved draft';$('task-frequency').value='monthly';$('task-interval').value='3';w.ElaraDialog.prompt=async()=> 'new tag';w.document.querySelector('#task-form [data-phase2-create="tag"]').click();await tick();assert.equal($('task-title').value,'saved draft');assert.equal($('task-frequency').value,'monthly');assert.equal($('task-interval').value,'3');assert.equal($('task-tag').value,'new tag');assert.ok(read().tags.includes('new tag'));
// The calendar handles selection and contains Persian day labels.
let chosen=null;w.ElaraCalendar.open(today,date=>chosen=date);const calendar=w.document.querySelector('.elara-calendar');assert.ok(calendar);assert.equal(calendar.dir,'rtl');calendar.querySelector('[data-day]').click();assert.ok(w.ElaraSchedule.validDate(chosen));
// Report empty state and true, explicit records only.
w.ElaraAccount={user:{uid:'test-only'}};w.ElaraOpen('reports');await tick();assert.equal(w.document.querySelectorAll('.report-empty').length,9); // habit data exists
const book=w.ElaraReading.record({id:'reading-test',title:'کتاب تست',totalPages:100,currentPage:0,shelf:'reading'},'count',53);w.ElaraReading.commit([book]);await tick();assert.ok(w.ElaraReports.data().reading.some(r=>r.value===53));assert.ok(w.document.querySelector('.report-chart svg'));
assert.deepEqual(errors,[]);console.log('PASS: Home day selection, canonical task/habit occurrence completion, XP idempotency, composer persistence, metadata draft preservation, calendar and report records');dom.window.close()})().catch(e=>{console.error(e);process.exit(1)});
