import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const source=readFileSync(new URL('../approved-language-journal.js',import.meta.url),'utf8');
const values=new Map();let blocked=false;
const submit={textContent:'ثبت گزارش',disabled:false},cancel={hidden:true};
const form={id:'learning-journal-form',elements:{date:{value:'2026-09-22'},minutes:{value:'30'},words:{value:'4'},note:{value:'draft'}},querySelector:s=>s==='[type=submit]'?submit:cancel,reset(){this.elements={date:{value:''},minutes:{value:''},words:{value:'0'},note:{value:''}}}};
const status={textContent:''};
const nodes={'learning-journal-form':form,'learning-journal-message':status};
const document={readyState:'loading',addEventListener(){},getElementById:id=>nodes[id]??null};
const sandbox={window:{ElaraAccount:{user:{uid:'A'}}},document,localStorage:{getItem:k=>values.get(k)??null,setItem(k,v){if(blocked)throw new Error('QuotaExceededError');values.set(k,v)}},console};
vm.runInNewContext(source,sandbox);
const {read,write,key,dateOK,validRow,syncAccount,save}=sandbox.window.ElaraLearningJournalTest;
const row=(id='a',extra={})=>({id,date:'2026-09-22',minutes:15,words:2,note:'ok',...extra});
assert.equal(read(null).length,0);assert.equal(write(null,[row()]),false);
assert.equal(write('A',[row()]),true);assert.equal(read('B').length,0);assert.equal(read('A')[0].id,'a');
values.set(key('A'),JSON.stringify([null,false,{},row('good'),row('bad-date',{date:'2026-02-30'}),row('bad-min',{minutes:'15'}),row('bad-words',{words:{}}),row('duplicate',{id:'good'}),row('legacy',{words:undefined,note:undefined})]));
assert.deepEqual(Array.from(read('A'),x=>x.id),['good','legacy']);
for(const bad of [null,1,[],{},row('x',{date:'invalid'}),row('x',{minutes:NaN}),row('x',{note:7})])assert.equal(validRow(bad),null);
values.set(key('A'),'{broken');assert.equal(read('A').length,0);
for(const date of ['2026-09-22','2024-02-29'])assert.equal(dateOK(date),true);
for(const date of ['2026-02-30','2026-13-01','x',null,99])assert.equal(dateOK(date),false);
assert.equal(syncAccount(),true);form.elements.date.value='2026-09-22';form.elements.minutes.value='30';form.elements.words.value='4';form.elements.note.value='Keep my draft';
blocked=true;assert.equal(write('A',[row()]),false);let prevented=false;save({preventDefault(){prevented=true},target:form});assert.equal(prevented,true);assert.match(status.textContent,/ذخیره انجام نشد/);assert.equal(form.elements.note.value,'Keep my draft');assert.equal(read('A').length,0);
blocked=false;save({preventDefault(){},target:form});assert.match(status.textContent,/ذخیره شد/);assert.equal(read('A')[0].note,'Keep my draft');
form.elements.note.value='SECRET DRAFT';sandbox.window.ElaraAccount.user={uid:'B'};assert.equal(syncAccount(),true);assert.equal(form.elements.note.value,'');assert.equal(status.textContent,'');assert.equal(read('B').length,0);assert.equal(read('A')[0].note,'Keep my draft');
sandbox.window.ElaraAccount.user=null;assert.equal(syncAccount(),true);assert.equal(read(null).length,0);
console.log('PASS: invalid rows, dates, storage-failure draft preservation, success, logout and UID isolation. Node VM only; not browser/Firebase.');
