import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const js=readFileSync(new URL('../approved-language-journal.js',import.meta.url),'utf8');
const store=new Map(),handlers={},events={};let blocked=false;
const node=(tag='div')=>({tag,dataset:{},children:[],textContent:'',append(...v){this.children.push(...v)},replaceChildren(){this.children=[]},focus(){this.focused=true}});
const history=node(),message=node();const submit=node('button'),cancel={hidden:true};
const form={id:'learning-journal-form',elements:{date:{value:'',focus(){}},minutes:{value:''},words:{value:'0'},note:{value:''}},querySelector(s){return s==='[type=submit]'?submit:cancel},reset(){this.elements.date.value='';this.elements.minutes.value='';this.elements.words.value='0';this.elements.note.value=''}};
const ids={'learning-journal-form':form,'learning-journal-message':message,'learning-journal-history':history};
const doc={readyState:'loading',getElementById:id=>ids[id]||null,createElement:node,createTextNode:text=>({textContent:text}),addEventListener:(name,fn)=>{handlers[name]=fn}};
const win={ElaraAccount:{user:{uid:'A'}},ElaraDialog:{confirm:async()=>true},addEventListener:(name,fn)=>{events[name]=fn}};
const ctx={window:win,document:doc,localStorage:{getItem:k=>store.get(k)||null,setItem(k,v){if(blocked)throw Error('quota');store.set(k,v)}},console};
vm.runInNewContext(js,ctx);handlers.DOMContentLoaded();
const {read,write,save}=win.ElaraLearningJournalTest;
const old={id:'old',date:'2026-09-21',minutes:18,words:3,note:'old note'};
write('A',[old]);events['elara:open']({detail:{tab:'language'}});
assert.ok(JSON.stringify(history.children).includes('old note'));
const target=(kind,id)=>({closest:s=>s==='#elara-learning-journal'?{}:s==='[data-journal-'+kind+']'?{dataset:{['journal'+kind[0].toUpperCase()+kind.slice(1)]:id}}:null});
handlers.click({target:target('edit','old')});assert.equal(form.elements.note.value,'old note');assert.equal(cancel.hidden,false);
form.elements.note.value='edited';form.elements.minutes.value='45';save({preventDefault(){},target:form});assert.equal(read('A')[0].note,'edited');
handlers.click({target:target('edit','old')});const cancelTarget={closest:s=>s==='#elara-learning-journal'||s==='[data-journal-cancel]'?{}:null};handlers.click({target:cancelTarget});assert.equal(cancel.hidden,true);assert.equal(form.elements.note.value,'');assert.equal(read('A')[0].note,'edited');
blocked=true;handlers.click({target:target('delete','old')});await new Promise(resolve=>setImmediate(resolve));assert.match(message.textContent,/حذف ذخیره نشد/);assert.equal(read('A').length,1);
blocked=false;handlers.click({target:target('delete','old')});await new Promise(resolve=>setImmediate(resolve));assert.equal(read('A').length,0);
write('A',[old]);events['elara:open']({detail:{tab:'language'}});form.elements.note.value='draft to clear';win.ElaraAccount.user={uid:'B'};events['elara:social-updated']();assert.equal(form.elements.note.value,'');assert.equal(history.children.length,2);assert.equal(read('B').length,0);
win.ElaraAccount.user=null;events['elara:auth-changed']();assert.equal(submit.disabled,true);
console.log('PASS: simulated DOM edit/save, cancel, delete failures/success, language reopen, UID switch and logout. NOT a real browser test.');
