import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';

const root=new URL('../',import.meta.url);
const read=name=>readFileSync(new URL(name,root),'utf8');
const boot=read('boot.js');
const css=read('visual-fidelity-pass5.css');
const profile=read('approved-profile-system.js');
const drawer=read('drawer.js');
const nav=read('approved-navigation-extension.js');

assert.ok(boot.indexOf("'visual-fidelity-pass4.css'")<boot.indexOf("'visual-fidelity-pass5.css'"),'Pass 5 CSS must load after Pass 4');
for(const family of ['default','minimal','rugged','anime'])assert.ok(css.includes(`body[data-elara-style="${family}"]`),`Pass 5 missing style family ${family}`);
for(const token of ['.elara-profile-identity-line','.elara-profile-xp-track','.elara-profile-chips','.pass5-profile-edit-preview'])assert.ok(css.includes(token),`Pass 5 profile styling missing ${token}`);
assert.ok(profile.includes('elara-profile-xp-track'),'Shared profile composition must render real XP progress');
assert.ok(profile.includes("editPreview=editView?'<div class=\"pass5-profile-edit-preview\">'"),'Profile editor must reuse the shared composition preview');
assert.ok(drawer.includes("styleTile('default','Elara Neon','فضایی، نئونی و سینمایی')"),'Default style must be visibly identified as Elara Neon without changing the stored key');
assert.ok(css.includes('grid-template-columns:minmax(188px,220px) minmax(0,1fr)'),'Desktop account drawer must expose menu rail + content workspace');
assert.ok(css.includes('width:min(92vw,430px)!important;height:100dvh!important'),'Mobile account drawer must use one coherent full-height side-drawer contract');
assert.ok(css.includes('@media(max-width:390px)'),'390px mobile fidelity guard missing');
assert.ok(css.includes('@media(max-width:340px)'),'narrow mobile fidelity guard missing');
assert.ok(css.includes('@media(prefers-reduced-motion:reduce)'),'Reduced-motion contract missing');
assert.ok(css.includes('body.light .elara-profile-composition'),'Light profile contract missing');
assert.ok(css.includes('body.dark.amoled .elara-profile-composition'),'AMOLED profile contract missing');
const mainSource=nav.match(/const MAIN=Object\.freeze\(\[([\s\S]*?)\]\);/)?.[1]||'';
const routes=[...mainSource.matchAll(/route:'([^']+)'/g)].map(m=>m[1]);
assert.deepEqual(routes,['exercise','language','tasks','home','ranking','books','freedom'],'Pass 5 must not regress canonical seven-route navigation');
assert.ok(drawer.includes("if(section==='home')renderHub()"),'Drawer home workspace must render instead of staying blank on desktop');
assert.ok(drawer.includes('class="pass5-drawer-hub"'),'Drawer hub markup missing');
assert.ok(css.includes('/* Pass 5B — Home reference fidelity.'),'Pass 5B Home layer missing');
assert.ok(css.includes('@media(min-width:1100px)'),'Desktop Home grid contract missing');
assert.ok(css.includes('.pass3-home .pass3-tasks-card{grid-column:span 5!important}'),'Desktop task-card hierarchy missing');
assert.ok(css.includes('.pass3-home .elara-dashboard-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important'),'Mobile two-column Home contract missing');
assert.ok(css.includes('@media(max-width:340px)'),'Narrow-phone single-column fallback missing');
assert.ok(css.includes('/* Pass 5C — Language reference fidelity.'),'Pass 5C Language layer missing');
assert.ok(css.includes('.pass3-language [data-language-block="leitner"]{grid-column:span 5!important}'),'Desktop Leitner layout missing');
assert.ok(css.includes('.pass3-language [data-language-block="books"]{grid-column:span 7!important}'),'Desktop language-books layout missing');
assert.ok(css.includes('@media(max-width:900px)'),'Language responsive breakpoint missing');
assert.ok(css.includes('@media(max-width:375px)'),'Narrow Language stacking guard missing');
assert.ok(css.includes('/* Pass 5D — Social and Ranking reference fidelity.'),'Pass 5D Social/Ranking layer missing');
assert.ok(css.includes('.pass3-ranking-list .pass3-rank-line.is-top-1{order:2'),'Real top-three podium ordering missing');
assert.ok(css.includes('.pass3-ranking-list .pass3-rank-line:nth-child(n+4){order:4;grid-column:1/-1}'),'Ranking continuation rows missing');
assert.ok(css.includes('.pass3-social-page .elara-social-grid>section:nth-child(2){grid-column:span 5!important}'),'Desktop friend-request layout missing');
assert.ok(css.includes('@media(max-width:430px)'),'Social mobile stacking guard missing');
console.log('PASS: Pass 5A/5B/5C/5D visual contract — neon profile/account/wardrobe, Home, Language, Social and Ranking fidelity; canonical data/navigation contracts preserved.');
