import assert from 'node:assert/strict';
import {planGroup,planClub,planChallenge,isExpiredPending,inspectCollab} from '../tools/social-cutover-core.mjs';
import {readFileSync} from 'node:fs';
const ts=ms=>({toMillis:()=>ms});
const oldGroup={owner:'owner',title:'Legacy Group',createdAt:ts(100),updatedAt:ts(100),lastText:'',lastSender:''};
assert.deepEqual(planGroup('g1',oldGroup),{status:'active'});
assert.equal(planGroup('g1',{...oldGroup,status:'active'}),null);
assert.throws(()=>planGroup('bad',{...oldGroup,owner:''}));
assert.equal(oldGroup.status,undefined,'Plan must not mutate input');
const oldClub={owner:'owner',title:'Legacy Club',kind:'reading',visibility:'public',assistant1:'',assistant2:'',restDay:5,createdAt:ts(10),updatedAt:ts(10)};
const members=[{uid:'owner',role:'owner'},{uid:'member',role:'member'}];
const clubPlan=planClub('c1',oldClub,members);
assert.equal(clubPlan.membershipMode,'invite','public visibility must not imply open membership');
assert.equal(clubPlan.memberCount,2,'real member count');
assert.equal(clubPlan.lastMembershipUid,'','no fabricated member event');
assert.equal(clubPlan.lastMembershipAction,'migration','neutral migration event');
assert.equal(clubPlan.status,'active');
assert.throws(()=>planClub('bad',oldClub,[]));
assert.throws(()=>planClub('bad',oldClub,[{uid:'outsider',role:'owner'}]));
assert.throws(()=>planClub('bad',oldClub,[...members,{uid:'newOwner',role:'owner'}]));
assert.throws(()=>planClub('partial',{...oldClub,membershipMode:'invite'},members));
assert.equal(planClub('modern',{...oldClub,...clubPlan},members),null);
const oldPending={from:'owner',to:'member',status:'pending',targetKind:'reading',targetText:'Read 12 pages',targetValue:12,createdAt:ts(100),expiresAt:ts(500)};
const oldAccepted={...oldPending,status:'accepted',respondedAt:ts(450)};
const stamp=ts(900);
const plan=planChallenge('legacy-id',oldPending,stamp,1000);
assert.deepEqual(Object.keys(plan).sort(),['attempt','mode','originId','updatedAt']);
assert.equal(plan.mode,'now');
assert.equal(plan.attempt,1);
assert.equal(plan.updatedAt,stamp);
assert.equal(planChallenge('legacy-id',oldPending,stamp,1000).originId,plan.originId,'idempotent deterministic origin');
assert.equal(isExpiredPending(oldPending,1000),true,'past pending challenge not revived');
assert.equal(planChallenge('accepted',oldAccepted,stamp,1000).mode,'now');
assert.equal(oldAccepted.status,'accepted','do not fake history');
assert.equal(oldAccepted.respondedAt.toMillis(),450,'preserve acceptance time');
assert.throws(()=>planChallenge('bad',{...oldPending,mode:'inbox'},stamp,1000));
assert.equal(planChallenge('modern',{...oldPending,...plan},stamp,1000),null);
assert.equal(inspectCollab({ownerUid:'owner',kind:'leitner-word'}).valid,true);
assert.equal(inspectCollab({ownerUid:'owner',kind:'goal'}).valid,true);
assert.equal(inspectCollab({ownerUid:'owner',kind:'unknown'}).valid,false);
const migrate=readFileSync(new URL('../tools/social-cutover-migrate.mjs',import.meta.url),'utf8');
assert.match(migrate,/args\.includes\('--apply'\)/);
assert.match(migrate,/ELARA_SOCIAL_CUTOVER_CONFIRM/);
assert.match(migrate,/lastUpdateTime/,'writes need optimistic precondition');
console.log('SOCIAL_CUTOVER_MIGRATION_UNIT_PASS deterministic=1 preserve-history=1 dry-run-default=1 guard=1');
