import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
const root = new URL('../',import.meta.url);
const html = readFileSync(new URL('index.html',root),'utf8');
const js = readFileSync(new URL('app.js',root),'utf8');
const css = readFileSync(new URL('styles.css',root),'utf8');
const phase2 = readFileSync(new URL('phase2.js',root),'utf8');
const social = readFileSync(new URL('elara-social.js',root),'utf8');
const design = readFileSync(new URL('elara-design.js',root),'utf8');
const rules = readFileSync(new URL('firestore.rules',root),'utf8');
const drawer = readFileSync(new URL('drawer.js',root),'utf8');
const dialog = readFileSync(new URL('dialog.js',root),'utf8');
const pass2 = readFileSync(new URL('visual-fidelity-pass2.js',root),'utf8');
const navigation = readFileSync(new URL('approved-navigation-extension.js',root),'utf8');
const profileSystem = readFileSync(new URL('approved-profile-system.js',root),'utf8');
const ids = new Set([...html.matchAll(/\bid="([^"]+)"/g)].map(match => match[1]));
assert.ok(ids.size > 50,'Application markup seems incomplete');
for (const [_,id] of js.matchAll(/\$\('([\w-]+)'\)/g)) {
  assert.ok(ids.has(id),`app.js references missing #${id}`);
}
for (const name of ['tasks','habits','goals','focus','books','words','settings']) {
  assert.ok(ids.has(`panel-${name}`),`Missing panel: ${name}`);
}
const mainSource=navigation.match(/const MAIN=Object\.freeze\(\[([\s\S]*?)\]\);/)?.[1]||'';
const mainRoutes=[...mainSource.matchAll(/route:'([^']+)',label:'([^']+)'/g)].map(m=>[m[1],m[2]]);
assert.deepEqual(mainRoutes,[['exercise','ورزش'],['language','زبان'],['tasks','تسک‌ها'],['home','خانه'],['ranking','رنکینگ'],['books','کتابخانه'],['freedom','آزادی']],'Canonical main navigation must stay at seven routes');
assert.equal(mainRoutes[3][0],'home','Home must remain the visual center route');
const initialBottom=html.match(/<nav class="bottom-nav"[^>]*data-elara-main-nav[^>]*>([\s\S]*?)<\/nav>/)?.[1]||'';
const initialRoutes=[...initialBottom.matchAll(/data-elara-tab="([^"]+)"/g)].map(m=>m[1]);
assert.deepEqual(initialRoutes,['exercise','language','tasks','social','home','ranking','books','freedom'],'Initial Bottom Nav must contain the eight real fallback destinations');
for(const route of initialRoutes)assert.match(initialBottom,new RegExp('href="#'+route+'"'),'Fallback Bottom Nav route '+route+' must work before JS hydration');
assert.match(html,/<a class="identity" href="#home"/,'Initial identity must point to Home');
for (const asset of ['styles.css','dialog.js','drawer.js','app.js','phase2.js']) assert.match(html,new RegExp(`(?:href|src)=["']${asset.replace('.', '\\.')}(?:\\?[^"']*)?["']`),`Missing asset: ${asset}`);
for (const token of ['recurrenceRule','occurrenceDone','focusSessions','data-focus-preset','task-priority-filter']) assert.ok(phase2.includes(token),`Phase 2 missing ${token}`);
for (const token of ['openSelfProfile','saveProfileValues','runTransaction','profilePublic','removeFriend']) assert.ok(social.includes(token),`Profile phase missing ${token}`);
assert.ok(html.includes('approved-profile-system.js'),'Shared profile system must load before account UI');
assert.ok(profileSystem.includes('window.ElaraProfileSystem=')&&profileSystem.includes('window.ElaraDialog.open')&&profileSystem.includes('saveProfileValues'),'Central profile editor/source of truth missing');
assert.ok(drawer.includes('function renderAccount()')&&!drawer.includes('id="drawer-account-form"'),'Drawer Account must be view-only with central edit dialog');
for (const token of ["['profile'",'data-elara-profile-self']) assert.ok(design.includes(token),`Profile navigation missing ${token}`);
assert.ok(drawer.includes('data-drawer-nav="help"'),'Help must live in the account/settings drawer');
for (const token of ['profilePublic','existsAfter','friendRequests']) assert.ok(rules.includes(token),`Firestore profile rules missing ${token}`);
for (const token of ['elara-account-menu-trigger','elara-top-more',"theme.insertAdjacentElement('afterend',trigger)",'data-drawer-nav="account"','data-folder-task-form','ElaraPrivateDrawer']) assert.ok(drawer.includes(token),`Private drawer missing ${token}`);
assert.equal((drawer.match(/class="elara-menu-bars"/g)||[]).length,1,'There must be exactly one hamburger account trigger source');
assert.ok(!drawer.includes("trigger.textContent='⋮'"),'Legacy vertical ellipsis trigger must be removed');
assert.ok(!drawer.includes('data-drawer-route="books"')&&!drawer.includes('data-drawer-route="words"'),'Product Library/Leitner routes must stay out of the account drawer');
assert.ok(drawer.includes('data-drawer-nav="language"')&&drawer.includes('data-approved-wardrobe'),'Drawer must keep app language and wardrobe account controls');
assert.ok(!design.includes("more.dataset.elaraMore=''"),'Legacy bottom-nav More trigger must not be created');
assert.ok(!design.includes("drawer.id='elara-more-drawer'"),'Legacy product More drawer must not be created');
const drawerMenu=drawer.match(/<nav class="drawer-menu">([\s\S]*?)<\/nav>/)?.[1]||'';
for(const route of ['home','tasks','habits','goals','focus','books','words','missions','social','ranking']) assert.ok(!drawerMenu.includes(`data-drawer-nav="${route}"`),`Product route ${route} must stay out of account drawer`);
for(const token of ['taskCompletionHistory','recordTaskCompletion','removeTaskCompletion']) assert.ok(js.includes(token),`Base task history missing ${token}`);
for(const token of ['ensureCompletionHistory','recordCompletion','removeCompletion','completedTodayCount']) assert.ok(phase2.includes(token),`Phase 2 task history missing ${token}`);
for(const token of ['lockViewport','unlockViewport',"position:'fixed'","root.hidden=true"]) assert.ok(dialog.includes(token),`Dialog viewport guard missing ${token}`);
for (const token of ['captureTaskDraft','restoreTaskDraft','task-short-description','task-description','openTaskDetails']) assert.ok(phase2.includes(token),`Task description/draft flow missing ${token}`);
const rpg=readFileSync(new URL('rpg.js',root),'utf8'),cloud=readFileSync(new URL('cloud.js',root),'utf8');
for (const token of ['rewardXp','mission-reward']) assert.ok(phase2.includes(token)||design.includes(token)||rpg.includes(token),`Mission reward UI missing ${token}`);
assert.ok(css.includes('Vazirmatn'),'Vazirmatn font must be the Persian UI default');
assert.ok(design.includes('elara-home-missions')&&design.includes('مأموریت‌های امروز'),'Missions must be visible on Home');
assert.ok(drawer.includes('data-folder-task-form'),'Folder drawer must support task creation inside each folder');
assert.ok(drawer.includes('data-drawer-nav="privacy"')&&drawer.includes('drawer-password-form'),'Private drawer security section missing');
assert.ok(drawer.includes('data-drawer-nav="appearance"')&&drawer.includes('data-drawer-nav="calendar"'),'Private drawer settings sections missing');
assert.ok(cloud.includes('changePassword:async'),'Account API must implement password change');
assert.ok(social.includes("await updateDoc(profileRef,{name})")&&social.includes("await updateDoc(profileRef,{bio})"),'Name and Bio must save independently');
for(const source of [js,phase2,drawer,design]) assert.ok(!/\bwindow\.(?:alert|confirm|prompt)\s*\(/.test(source),'Native browser dialogs are forbidden');
for (const token of ['ElaraDialog','role="dialog"','aria-modal="true"']) assert.ok(dialog.includes(token),`Dialog system missing ${token}`);
for (const token of ['task-short-description','task-description','view-task','openTaskDetails']) assert.ok(phase2.includes(token),`Task details missing ${token}`);
assert.ok(!/<script[^>]+src="http/.test(html),'Core functionality must not depend on remote scripts');
for(const token of ['restoreLeitner','reorderHome','enforceWellnessPrivacy']) assert.ok(pass2.includes(token),`Visual Pass 2 missing ${token}`);
assert.ok(!pass2.includes('function pruneSidebar')&&!pass2.includes("remove=new Set(['tasks'"),'Visual Pass 2 must not mutate canonical Sidebar navigation');
assert.ok(drawer.includes("if(section==='privacy')renderPrivacy()")&&drawer.includes('pass2-privacy-list'),'Drawer must render the complete Privacy Center directly');
assert.ok(!pass2.includes('function upgradePrivacy')&&!pass2.includes('setTimeout(upgradePrivacy'),'Privacy must not depend on a delayed Pass 2 overwrite');
assert.ok(css.includes('@media(max-width:700px)'),'Mobile layout is missing');
const reading=readFileSync(new URL('reading.js',root),'utf8');
assert.ok(social.includes('activityVisibility')&&social.includes("['private','friends','public']"),'Social activity visibility must support private/friends/public');
assert.ok(drawer.includes('elara_activity_visibility_')&&drawer.includes('SHARE_KEYS')&&drawer.includes('value="private"')&&drawer.includes('value="friends"')&&drawer.includes('value="public"'),'Privacy drawer must expose granular private/friends/public activity choices');
assert.ok(!reading.includes("visibility:'friends'"),'Reading reports must not bypass configured activity privacy');
for(const token of ["resource.data.visibility == 'public'","request.resource.data.type == 'reading'","request.resource.data.type == 'book_clip'","'visibility','category'"])assert.ok(rules.includes(token),'Firestore activity privacy contract missing '+token);
assert.ok(social.includes("book_clip:'reading'")&&social.includes("if(type==='book_clip')"),'Social service must publish safe book clips through reading privacy');
for(const token of ['canReadActivity','canReadPost','match /likes/{likeId}','match /comments/{commentId}','request.resource.data.text.size() <= 1000'])assert.ok(rules.includes(token),'Social engagement rules missing '+token);
for(const token of ["match /conversations/{conversationId}","match /messages/{messageId}","friendOf(request.resource.data.members[0]","request.resource.data.text.size() <= 2000"])assert.ok(rules.includes(token),'Firestore DM contract missing '+token);
for(const token of ["match /socialPosts/{postId}","match /socialStories/{storyId}","duration.value(24, 'h')","text.size() <= 4000","text.size() <= 1000"])assert.ok(rules.includes(token),'Page/Story Firestore contract missing '+token);
for(const token of ["window.ElaraSocial.dm=","async function sendDm","function listenDm","where('members','array-contains',uid)"])assert.ok(social.includes(token),'Social DM service missing '+token);
const pageService=readFileSync(new URL('elara-page.js',root),'utf8'),pageView=readFileSync(new URL('page-view.js',root),'utf8'),firestoreIndexes=JSON.parse(readFileSync(new URL('firestore.indexes.json',root),'utf8'));for(const token of ['socialPosts','socialStories','createPost','createStory'])assert.ok(pageService.includes(token),'Page service missing '+token);assert.ok(pageView.includes('data-page-post-form')&&pageView.includes('data-page-story-form'),'Page UI forms missing');
assert.ok(pageService.includes("where('expiresAt','>',Timestamp.now())"),'Story friend query must enforce expiry server-side');assert.ok(firestoreIndexes.indexes.some(x=>x.collectionGroup==='socialStories'&&x.fields.some(f=>f.fieldPath==='expiresAt')),'socialStories expiry composite index missing');
console.log(`Static check passed: ${ids.size} HTML ids, base panels, canonical seven-route navigation, local assets, phase 2 recurrence/focus module and selector references.`);
