import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
const root = new URL('../',import.meta.url);
const html = readFileSync(new URL('index.html',root),'utf8');
const js = readFileSync(new URL('app.js',root),'utf8');
const css = readFileSync(new URL('styles.css',root),'utf8');
const phase2 = readFileSync(new URL('phase2.js',root),'utf8');
const social = readFileSync(new URL('elara-social.js',root),'utf8');
const design = readFileSync(new URL('elara-design.js',root),'utf8');
const rules = readFileSync(new URL('firestore.rules',root),'utf8');
const drawer = readFileSync(new URL('drawer.js',root),'utf8');
const dialog = readFileSync(new URL('dialog.js',root),'utf8');
const pass2 = readFileSync(new URL('visual-fidelity-pass2.js',root),'utf8');
const navigation = readFileSync(new URL('approved-navigation-extension.js',root),'utf8');
const featureHubs = readFileSync(new URL('feature-hubs-2026.js',root),'utf8');
const taskGoalFinal = readFileSync(new URL('task-goal-final-2026.css',root),'utf8');
const rpg = readFileSync(new URL('rpg.js',root),'utf8');
const linkedTasks = readFileSync(new URL('linked-tasks.js',root),'utf8');
const taskChecklist = readFileSync(new URL('task-checklist.js',root),'utf8');
const referenceHome = readFileSync(new URL('reference-home-shell-2026.js',root),'utf8');
const profileSystem = readFileSync(new URL('approved-profile-system.js',root),'utf8');
const profileGalleryCss = readFileSync(new URL('profile-gallery-2026.css',root),'utf8');
const collab = readFileSync(new URL('elara-collab.js',root),'utf8');
const collabCss = readFileSync(new URL('collab-2026.css',root),'utf8');
const languageClasses = readFileSync(new URL('language-custom-classes.js',root),'utf8');
const bootSource = readFileSync(new URL('boot.js',root),'utf8');
const ids = new Set([...html.matchAll(/\bid="([^"]+)"/g)].map(match => match[1]));
assert.ok(ids.size > 50,'Application markup seems incomplete');
const optionalDynamicIds=new Set(['word-share-friend']);
for (const [_,id] of js.matchAll(/\$\('([\w-]+)'\)/g)) {
  if(optionalDynamicIds.has(id))continue;
  assert.ok(ids.has(id),`app.js references missing #${id}`);
}
for (const name of ['tasks','habits','goals','focus','books','words','settings']) {
  assert.ok(ids.has(`panel-${name}`),`Missing panel: ${name}`);
}
const mainSource=navigation.match(/const MAIN=Object\.freeze\(\[([\s\S]*?)\]\);/)?.[1]||'';
const mainRoutes=[...mainSource.matchAll(/route:'([^']+)',label:'([^']+)'/g)].map(m=>[m[1],m[2]]);
assert.deepEqual(mainRoutes,[['exercise','ورزش و سلامتی'],['language','زبان'],['tasks','کارها'],['home','خانه'],['ranking','رتبه‌بندی'],['books','کتابخانه'],['freedom','آزادی']],'Canonical main navigation must stay at seven routes with approved Persian labels');
assert.equal(mainRoutes[3][0],'home','Home must remain the visual center route');
const initialBottom=html.match(/<nav class="bottom-nav"[^>]*data-elara-main-nav[^>]*>([\s\S]*?)<\/nav>/)?.[1]||'';
const initialRoutes=[...initialBottom.matchAll(/data-elara-tab="([^"]+)"/g)].map(m=>m[1]);
assert.deepEqual(initialRoutes,['blog','books','social','home','tasks','freedom','page'],'Initial Bottom Nav must keep Home centered with Tasks right and Friends left');
for(const route of initialRoutes)assert.match(initialBottom,new RegExp('href="#'+route+'"'),'Fallback Bottom Nav route '+route+' must work before JS hydration');
assert.match(html,/<a class="identity" href="#home"/,'Initial identity must point to Home');
for (const asset of ['styles.css','dialog.js','drawer.js','app.js','phase2.js']) assert.match(html,new RegExp(`(?:href|src)=["']${asset.replace('.', '\\.')}(?:\\?[^"']*)?["']`),`Missing asset: ${asset}`);
for (const token of ['recurrenceRule','occurrenceDone','focusSessions','data-focus-preset','task-priority-filter']) assert.ok(phase2.includes(token),`Phase 2 missing ${token}`);
for (const token of ['openSelfProfile','saveProfileValues','runTransaction','profilePublic','removeFriend']) assert.ok(social.includes(token),`Profile phase missing ${token}`);
assert.ok(html.includes('approved-profile-system.js'),'Shared profile system must load before account UI');
assert.ok(profileSystem.includes('window.ElaraProfileSystem=')&&profileSystem.includes('window.ElaraDialog.open')&&profileSystem.includes('saveProfileValues'),'Central profile editor/source of truth missing');
for(const token of ['profile-avatar-gallery','data-profile-avatar-choice','galleryOpen=false','عکس از گالری دستگاه','photoMode.value=\'elara\''])assert.ok(profileSystem.includes(token),'Profile avatar gallery contract missing '+token);
assert.ok(drawer.includes('data-profile-avatar-gallery')&&drawer.includes('openEditor?.({galleryOpen:true})'),'Settings Profile must expose the avatar gallery directly');
for(const token of ['.profile-avatar-gallery-grid','.profile-avatar-gallery-item.is-active','.profile-device-photo-button'])assert.ok(profileGalleryCss.includes(token),'Profile gallery responsive CSS missing '+token);
assert.ok(bootSource.includes("./elara-collab.js")&&bootSource.includes("'collab-2026.css'"),'Collaboration runtime/CSS must load from boot');
for(const token of ['collabSpaces','collabInvites','collabLinks','shareEntity','acceptInvite','declineInvite','joinLink','memberRows','startInviteRealtime','stopInviteRealtime','pendingInvites',"['task','habit','goal','language-class','leitner-word']"])assert.ok(collab.includes(token),'Collaboration service missing '+token);
for(const token of ['match /collabSpaces/{spaceId}','match /collabInvites/{inviteId}','match /collabLinks/{token}','isCollabMember','isCollabOwner',"validCollabKind"])assert.ok(rules.includes(token),'Firestore collaboration contract missing '+token);
for(const token of ['studyHoursPerDay','sessionsPerDay','data-class-add-type="offline"','data-class-add-type="online"','data-class-add-type="linked"','data-class-share','data-class-classmates','data-class-share-link','collabRole===\'member\''])assert.ok(languageClasses.includes(token),'Custom class collaboration/pacing missing '+token);
for(const token of ['share-task','shared-task','share-habit','shared-habit','astra-shared-chip','entity-shared-chip'])assert.ok(phase2.includes(token),'Task/Habit collaboration surface missing '+token);
for(const token of ['word-share-friend','share-word','shared-word','leitner-word'])assert.ok(js.includes(token)||collab.includes(token),'Leitner collaboration surface missing '+token);
for(const token of ['.collab-inbox-dialog','.collab-member-list','.language-class-type-adders','.word-share-on-add','.astra-shared-chip'])assert.ok(collabCss.includes(token),'Collaboration responsive CSS missing '+token);

assert.ok(drawer.includes('function renderAccount()')&&!drawer.includes('id="drawer-account-form"'),'Drawer Account must be view-only with central edit dialog');
for (const token of ["['profile'",'data-elara-profile-self']) assert.ok(design.includes(token),`Profile navigation missing ${token}`);
assert.ok(drawer.includes('data-drawer-nav="help"'),'Help must live in the account/settings drawer');
for (const token of ['profilePublic','existsAfter','friendRequests']) assert.ok(rules.includes(token),`Firestore profile rules missing ${token}`);
for (const token of ['elara-account-menu-trigger','elara-top-more',"theme.insertAdjacentElement('afterend',trigger)",'data-drawer-nav="account"','data-folder-task-form','ElaraPrivateDrawer']) assert.ok(drawer.includes(token),`Private drawer missing ${token}`);
assert.equal((drawer.match(/class="elara-menu-bars"/g)||[]).length,1,'There must be exactly one hamburger account trigger source');
assert.ok(!drawer.includes("trigger.textContent='⋮'"),'Legacy vertical ellipsis trigger must be removed');
assert.ok(!drawer.includes('data-drawer-route="books"')&&!drawer.includes('data-drawer-route="words"'),'Product Library/Leitner routes must stay out of the account drawer');
assert.ok(drawer.includes('data-drawer-nav="language"')&&drawer.includes('data-approved-wardrobe'),'Drawer must keep app language and wardrobe account controls');
assert.ok(!design.includes("more.dataset.elaraMore=''"),'Legacy bottom-nav More trigger must not be created');
assert.ok(!design.includes("drawer.id='elara-more-drawer'"),'Legacy product More drawer must not be created');
const drawerMenu=drawer.match(/<nav class="drawer-menu">([\s\S]*?)<\/nav>/)?.[1]||'';
for(const route of ['home','tasks','habits','goals','focus','books','words','missions','social','ranking']) assert.ok(!drawerMenu.includes(`data-drawer-nav="${route}"`),`Product route ${route} must stay out of account drawer`);
for(const token of ['taskCompletionHistory','recordTaskCompletion','removeTaskCompletion']) assert.ok(js.includes(token),`Base task history missing ${token}`);
assert.ok(js.includes('manualOrder:t.manualOrder!=null')&&phase2.includes('manualOrder'),'Task manual order must survive normalize and participate in render sorting');
for(const token of ['ensureCompletionHistory','recordCompletion','removeCompletion','completedTodayCount']) assert.ok(phase2.includes(token),`Phase 2 task history missing ${token}`);
for(const token of ['lockViewport','unlockViewport',"position:'fixed'","root.hidden=true"]) assert.ok(dialog.includes(token),`Dialog viewport guard missing ${token}`);
for (const token of ['captureTaskDraft','restoreTaskDraft','task-short-description','task-description','openTaskDetails']) assert.ok(phase2.includes(token),`Task description/draft flow missing ${token}`);
const cloud=readFileSync(new URL('cloud.js',root),'utf8');
for (const token of ['rewardXp','mission-reward']) assert.ok(phase2.includes(token)||design.includes(token)||rpg.includes(token),`Mission reward UI missing ${token}`);
assert.ok(css.includes('Vazirmatn'),'Vazirmatn font must be the Persian UI default');
assert.ok(design.includes('elara-home-missions')&&design.includes('مأموریت‌های امروز'),'Missions must be visible on Home');
assert.ok(drawer.includes('data-folder-task-form'),'Folder drawer must support task creation inside each folder');
assert.ok(drawer.includes('data-drawer-nav="privacy"')&&drawer.includes('drawer-password-form'),'Private drawer security section missing');
assert.ok(drawer.includes('data-drawer-nav="appearance"')&&drawer.includes('data-drawer-nav="calendar"'),'Private drawer settings sections missing');
assert.ok(cloud.includes('changePassword:async'),'Account API must implement password change');
assert.ok(social.includes("await updateDoc(profileRef,{name})")&&social.includes("await updateDoc(profileRef,{bio})"),'Name and Bio must save independently');
for(const source of [js,phase2,drawer,design]) assert.ok(!/\bwindow\.(?:alert|confirm|prompt)\s*\(/.test(source),'Native browser dialogs are forbidden');
for (const token of ['ElaraDialog','role="dialog"','aria-modal="true"']) assert.ok(dialog.includes(token),`Dialog system missing ${token}`);
for (const token of ['task-short-description','task-description','view-task','openTaskDetails']) assert.ok(phase2.includes(token),`Task details missing ${token}`);
assert.ok(!/<script[^>]+src="http/.test(html),'Core functionality must not depend on remote scripts');
for(const token of ['restoreLeitner','reorderHome','enforceWellnessPrivacy']) assert.ok(pass2.includes(token),`Visual Pass 2 missing ${token}`);
assert.ok(!pass2.includes('function pruneSidebar')&&!pass2.includes("remove=new Set(['tasks'"),'Visual Pass 2 must not mutate canonical Sidebar navigation');
assert.ok(drawer.includes("if(section==='privacy')renderPrivacy()")&&drawer.includes('pass2-privacy-list'),'Drawer must render the complete Privacy Center directly');
assert.ok(!pass2.includes('function upgradePrivacy')&&!pass2.includes('setTimeout(upgradePrivacy'),'Privacy must not depend on a delayed Pass 2 overwrite');
assert.ok(css.includes('@media(max-width:700px)'),'Mobile layout is missing');
const reading=readFileSync(new URL('reading.js',root),'utf8');
assert.ok(social.includes('activityVisibility')&&social.includes("['private','friends','public']"),'Social activity visibility must support private/friends/public');
assert.ok(drawer.includes('elara_activity_visibility_')&&drawer.includes('SHARE_KEYS')&&drawer.includes('value="private"')&&drawer.includes('value="friends"')&&drawer.includes('value="public"'),'Privacy drawer must expose granular private/friends/public activity choices');
assert.ok(!reading.includes("visibility:'friends'"),'Reading reports must not bypass configured activity privacy');
for(const token of ["resource.data.visibility == 'public'","request.resource.data.type == 'reading'","request.resource.data.type == 'book_clip'","request.resource.data.type == 'focus'","'visibility','category'"])assert.ok(rules.includes(token),'Firestore activity privacy contract missing '+token);
assert.ok(social.includes("book_clip:'reading'")&&social.includes("if(type==='book_clip')"),'Social service must publish safe book clips through reading privacy');
assert.ok(drawer.includes("'focus'")&&drawer.includes("select('focus',local.focus)"),'Privacy drawer must expose independent Focus sharing');
assert.ok(social.includes("focus:'focus'")&&social.includes("if(type==='focus')")&&social.includes('safe.durationMin'),'Social service must publish bounded Focus activity');
assert.ok(rules.includes("'durationMin','tag'")&&rules.includes("request.resource.data.durationMin <= 180"),'Focus activity Rules must bound duration and tag');
for(const token of ['canReadActivity','canReadPost','match /likes/{likeId}','match /comments/{commentId}','request.resource.data.text.size() <= 1000'])assert.ok(rules.includes(token),'Social engagement rules missing '+token);
const engagementView=readFileSync(new URL('social-engagement-view.js',root),'utf8'),socialView=readFileSync(new URL('social-view.js',root),'utf8'),engagementPageView=readFileSync(new URL('page-view.js',root),'utf8');for(const token of ['data-engagement-like','data-engagement-comment','ElaraEngagementView'])assert.ok(engagementView.includes(token),'Engagement view missing '+token);assert.ok(socialView.includes('data-engagement-kind="activity"')&&engagementPageView.includes('data-engagement-kind="post"'),'Activity and Page must expose shared engagement controls');
for(const token of ["match /conversations/{conversationId}","match /messages/{messageId}","friendOf(request.resource.data.members[0]","request.resource.data.text.size() <= 2000"])assert.ok(rules.includes(token),'Firestore DM contract missing '+token);
for(const token of ["match /blocks/{blockId}","function blockedBetween","!blockedBetween(request.auth.uid, uid)","!blockedBetween(resource.data.members[0], resource.data.members[1])"])assert.ok(rules.includes(token),'Firestore block contract missing '+token);
for(const token of ["async function blockUser","async function unblockUser","state.blocked","window.ElaraSocial.blockUser"])assert.ok(social.includes(token),'Social block service missing '+token);
assert.ok(drawer.includes('data-social-unblock')&&drawer.includes('pass2-blocked-list'),'Privacy drawer must expose blocked-account management');
for(const token of ["match /socialPosts/{postId}","match /socialStories/{storyId}","duration.value(24, 'h')","text.size() <= 4000","text.size() <= 1000"])assert.ok(rules.includes(token),'Page/Story Firestore contract missing '+token);
for(const token of ["match /contentReports/{reportId}","canReadStory","request.resource.data.reason in ['spam','harassment','hate','sexual','violence','privacy','other']","allow update, delete: if false"])assert.ok(rules.includes(token),'Content report Firestore contract missing '+token);
for(const token of ["window.ElaraSocial.dm=","async function sendDm","function listenDm","where('members','array-contains',uid)"])assert.ok(social.includes(token),'Social DM service missing '+token);
for(const token of ['window.ElaraSocial.groups=','async function createGroup','collectionGroup(db,\'groupMembers\')','writeBatch(db)','async function sendGroup'])assert.ok(social.includes(token),'Social group service missing '+token);for(const token of ['match /groups/{groupId}','match /groupMembers/{memberId}','isGroupMember','getAfter(groupPath(groupId))','match /{path=**}/groupMembers/{memberId}'])assert.ok(rules.includes(token),'Firestore group contract missing '+token);
const groupsView=readFileSync(new URL('social-groups-ui.js',root),'utf8');for(const token of ['data-social-create-group','data-social-open-group','data-group-quick','ElaraSocialGroupsUI'])assert.ok(groupsView.includes(token),'Group UI missing '+token);
const pageService=readFileSync(new URL('elara-page.js',root),'utf8'),pageView=readFileSync(new URL('page-view.js',root),'utf8'),firestoreIndexes=JSON.parse(readFileSync(new URL('firestore.indexes.json',root),'utf8'));for(const token of ['socialPosts','socialStories','createPost','createStory'])assert.ok(pageService.includes(token),'Page service missing '+token);for(const token of ['getStorage','uploadBytes','getBytes','deleteObject','pageMedia/','validateMedia'])assert.ok(pageService.includes(token),'Page secure media service missing '+token);assert.ok(pageView.includes('data-page-post-form')&&pageView.includes('data-page-story-form'),'Page UI forms missing');for(const token of ['data-page-media-input','data-page-media-remove','page-media','mediaMarkup'])assert.ok(pageView.includes(token),'Page media UI missing '+token);
for(const token of ['editPost','reportContent',"doc(db,'contentReports',reportId)"])assert.ok(pageService.includes(token),'Page moderation/edit service missing '+token);
assert.ok(pageService.includes("where('expiresAt','>',Timestamp.now())"),'Story friend query must enforce expiry server-side');assert.ok(firestoreIndexes.indexes.some(x=>x.collectionGroup==='socialStories'&&x.fields.some(f=>f.fieldPath==='expiresAt')),'socialStories expiry composite index missing');

for(const token of ['match /clubs/{clubId}','canCreateClub()','isClubManager(id)','clubInvites','clubPosts','request.resource.data.kind in [\'mission\',\'poll\']'])assert.ok(rules.includes(token),'Club security contract missing '+token);
for(const token of ['match /challenges/{challengeId}',"duration.value(25, 's')",'quickMessages',"request.resource.data.status in ['accepted','declined']"])assert.ok(rules.includes(token),'Challenge security contract missing '+token);
for(const token of ['ElaraSocial.challenges=','createChallenge','respondChallenge','challengeQuick','CHALLENGE_QUICK'])assert.ok(social.includes(token),'Challenge service contract missing '+token);
for(const token of ['ElaraSocial.clubs=','createClub','setClubAssistant','createClubPost','voteClubPoll'])assert.ok(social.includes(token),'Club service contract missing '+token);
console.log(`Static check passed: ${ids.size} HTML ids, base panels, canonical seven-route navigation, local assets, phase 2 recurrence/focus module and selector references.`);

const taskBulkSource=readFileSync(new URL('task-bulk-reorder.js',root),'utf8');for(const token of ['data-task-bulk','data-task-drag','persistDomOrder','bulkDuplicate','bulkMove','pointerdown','ArrowUp'])assert.ok(taskBulkSource.includes(token),'Task bulk/reorder missing '+token);
const universalTaskSource=readFileSync(new URL('task-universal-interactions.js',root),'utf8'),universalTaskCss=readFileSync(new URL('task-universal-interactions.css',root),'utf8');
for(const token of ['feature-section-task-row','task-board-card','#panel-home .ref-task-row','task-archive-row','task-daily-target-chip','task-trash-drop',"taskAction?.('delete-task'"])assert.ok(universalTaskSource.includes(token),'Universal task interaction missing '+token);
for(const token of ['#task-trash-drop','#task-universal-drag-ghost','.task-daily-target-chip','is-universal-task-dragging'])assert.ok(universalTaskCss.includes(token),'Universal task interaction CSS missing '+token);
assert.ok(phase2.includes('تکرار در روز')&&phase2.includes('task-daily-target'),'All task composers/details must expose repeat-per-day');
assert.ok(phase2.includes("if(action==='edit-task'){await openTaskDetails(task,{collapsed:false});return;}"),'Task edit must open the reliable expanded detail editor');
for(const token of ['beginTaskCardReorder','moveTaskCardReorder','task-card-reordering','persistDomOrder'])assert.ok(phase2.includes(token),'Whole-card task reorder missing '+token);
for(const token of ["source-goal","source-exercise","source-language","source-book","source-focus","astra-task-status","astra-task-core-meta"])assert.ok(phase2.includes(token)||css.includes(token),'Task source/status treatment missing '+token);
assert.ok(featureHubs.includes("sectionTasks(lp,'language','language')")&&featureHubs.includes("sectionTasks(parent,'focus','focus')"),'Leitner and Focus must expose the shared task composer');
assert.ok(phase2.includes("['book','language','exercise','focus'].includes"),'Task composer must preserve Focus/Book/Language/Exercise source groups');
assert.ok(phase2.includes("['task','habit'].includes(prefix)")&&phase2.includes('habitDailyProgress')&&phase2.includes("syncDailyTargetVisibility('habit')"),'Habits must share the repeat-per-day toggle and counted daily progress');
assert.ok(html.includes('goal-daily-target-enabled')&&html.includes('goal-daily-target-options'),'Goals must expose repeat-per-day controls in their form');
assert.ok(js.includes('goalDailyProgress')&&js.includes("toggle-goal-daily")&&js.includes('dailyProgress:safeDailyProgress'),'Goals must persist and count repeat-per-day progress');
for(const token of ['goal-date','goal-time','goal-priority','goal-list-name','goal-folder','goal-tag','goal-recurrence'])assert.ok(html.includes('id="'+token+'"'),'Goal task-like setting missing #'+token);
for(const token of ['editGoalStep','goalStepDailyProgress','goalStepDone','edit-step','step-dialog-weekday','recurrenceRule:safeRule(step.recurrenceRule'])assert.ok(js.includes(token),'Rich goal substep behavior missing '+token);
for(const token of ["spec.time!==undefined","spec.folder!==undefined","spec.recurrenceRule!==undefined","sourceType:'goal-step'"])assert.ok(linkedTasks.includes(token),'Linked goal-step metadata projection missing '+token);
assert.ok(rpg.includes('mission-back-home')&&rpg.includes('data-elara-tab="home"'),'All Missions page must provide return-to-home action');
for(const token of ['.astra-task-core-meta','display:flex!important','touch-action:none!important','.astra-task-status','.goal-repeat-strip','.compact-toggle'])assert.ok(taskGoalFinal.includes(token),'Final task/goal ownership CSS missing '+token);
assert.ok(phase2.includes('astra-time-chip')&&phase2.includes("document.getSelection?.()?.removeAllRanges?.()"),'Task cards must expose time metadata and suppress text selection during reorder');
assert.ok(phase2.includes('task-checklist-preview')&&phase2.includes('data-phase2-action="view-task"')&&phase2.includes("openTaskDetails(task,{collapsed:true})"),'Task title click must open compact details and render nested checklist preview');
assert.ok(phase2.includes('elapsed<170')&&phase2.includes("hold.pointerType==='touch'"),'Mobile normal-mode task reorder must distinguish quick scroll from hold-drag');
for(const token of ['feature-section-task-more','data-section-task-actions',"taskAction?.('view-task'","parentBack(parent,'home')"])assert.ok(featureHubs.includes(token),'Section task/back contract missing '+token);
for(const token of ['task hierarchy + stronger source identity','.task-checklist-preview','.feature-section-task-more','.feature-parent-back','feature-section-task-row.source-exercise','user-select:none!important'])assert.ok(taskGoalFinal.includes(token),'Task hierarchy/source/back CSS missing '+token);
assert.ok(js.includes('task-checklist-preview')&&js.includes('const canonical=window.ElaraTasks?.render'),'Fallback renderer must preserve checklist hierarchy and defer to canonical Tasks');
assert.ok(phase2.includes('selectTaskByHold')&&phase2.includes('window.ElaraTaskBulk')&&!phase2.includes('navigator.vibrate?.(16);void openTaskQuickActions(id)'), 'Long press must enter bulk selection instead of opening the single-task action sheet');
assert.ok(referenceHome.includes('ref-task-subitems')&&referenceHome.includes('data-task-source')&&referenceHome.includes("sourceClass=t=>"),'Home Today tasks must preserve source identity and nested checklist previews');
for(const token of ['Telegram-style task selection + brighter task hierarchy','#task-bulk-toolbar','.is-selected::after','.ref-task-subitems','source-goal','source-language','source-exercise'])assert.ok(taskGoalFinal.includes(token),'Telegram selection/home source color CSS missing '+token);
assert.ok(taskChecklist.includes('function toggleItem(')&&taskChecklist.includes('[data-task-check-toggle][data-task-id][data-check-id]'),'Nested checklist items must be directly toggleable from task surfaces');
assert.ok(phase2.includes('task-checklist-preview-item')&&phase2.includes('data-task-check-toggle')&&js.includes('task-checklist-preview-item'),'Canonical and fallback task renderers must expose full nested task rows');
assert.ok(referenceHome.includes('data-task-check-toggle')&&referenceHome.includes('data-check-id'),'Home Today nested task items must be checkable');
for(const token of ['v14: clean selection, full nested task rows, softer source cards','left:8px!important','.task-checklist-preview-item','border-radius:16px!important','#task-bulk-toolbar .task-delete-scope'])assert.ok(taskGoalFinal.includes(token),'Task v14 selection/subtask polish missing '+token);
assert.ok(taskChecklist.includes('description:String(x.description||\'\')')&&taskChecklist.includes('data-check-description')&&taskChecklist.includes('async function editItem')&&taskChecklist.includes('data-task-check-edit'),'Subtasks must persist descriptions and expose independent editing');
assert.ok(js.includes('description:asText(x.description,1600)'),'App hydration must preserve subtask descriptions');
assert.ok(phase2.includes('task-detail-settings')&&phase2.includes("openTaskDetails(task,{collapsed:false})"),'Task details must support collapsed title-open and fully expanded kebab edit modes');
for(const token of ['v15: teal selection, compact detail disclosure, editable subtasks','#58ded2','.task-detail-settings','.task-checklist-preview-edit','.ref-task-subitem-check'])assert.ok(taskGoalFinal.includes(token),'Task v15 polish missing '+token);




assert.ok(rules.includes('match /socialStats/{uid}')&&rules.includes("request.resource.data.streak <= 36500"),'Social streak stats must have privacy-aware Firestore rules');
assert.ok(social.includes("doc(db,'socialStats',uid)")&&social.includes('visibleSocialStats')&&social.includes("activityVisibility(uid,'streak')"),'Social service must sync and read privacy-aware streak stats');
assert.ok(socialView.includes('social-streak')&&socialView.includes('Number.isInteger(Number(p.streak))'),'Friends/Ranking must render only real streak values');

const storageRules=readFileSync(new URL('storage.rules',root),'utf8');for(const token of ["match /pageMedia/{uid}/{kind}/{contentId}/{fileName}","image/(jpeg|png|webp)","kind in ['post','story']",'canReadStory','canReadPost'])assert.ok(storageRules.includes(token),'Storage media rules must include '+token);

for(const token of ["'mediaPath','mediaType'","/post/' + postId","/story/' + storyId","mediaType in ['image/jpeg','image/png','image/webp']"])assert.ok(rules.includes(token),'Page media Firestore metadata contract missing '+token);

const notifications=readFileSync(new URL('notifications.js',root),'utf8');for(const token of ["const tt=","Friend request","Mark all read","No new notifications","elara:locale-changed","focus:'🧠'"])assert.ok(notifications.includes(token),'Notification i18n/focus contract missing '+token);
